### ISSUE TITLE
那么多人赞的 我就不说了 只是看到那么多句号 略感瑕疵

### ISSUE THREAD

**Issue by cnwhy** [LingDong-/wenyan-lang#101]
建议很多没必要的地方就不要用句号了, 实在不能省略的地方用 `空格` 和 `畢` 处理可否

**Comment by rikakomoe** [comment]
这是个 code style 的问题，所有的句号都可以省略或者换成空格的。

是时候出个 style guide 了！（x

**Comment by AAChartModel** [comment]
确实,古文言文都是没有标点符号的,标点符号是西化的产物

**Comment by Quenii** [comment]
句读之不知 惑之不解...

**Comment by EndlessCheng** [comment]
https://www.zhihu.com/question/19646540
看完你还觉得瑕疵吗？

**Comment by ZeroAurora** [comment]
符号、空格可任意替换
