### ISSUE TITLE
is:issue is:open 这个比那个易语言可强多了

### ISSUE THREAD

**Issue by dengzl0217** [LingDong-/wenyan-lang#106]
is:issue is:open 这个比那个易语言可强多了

**Comment by BlankRain** [comment]
易语言是VB...

**Comment by Saafo** [comment]
有一说一这个实现原理也不是很难吧，基本的词法分析和语法分析（需要语法分析吗）然后将词语转换成JS就完事了，本质上还是基于JS的，只是套了一层皮，不过创意太好啦（若有误请指正
