### ISSUE TITLE
I got an error( 'hanzi2num is not a function') when I wanted to render my own program

### ISSUE THREAD

**Issue by forblanca** [LingDong-/wenyan-lang#115]
Program can be compiled into a js file and run normally, but it cannot be rendered as printed book. 
Display a TypeError : hanzi2num is not a function at endnum (parser.js:129:23)
The code looks all fine
Sorry I'm not very familiar with js 😂
waiting for your answer

**Comment by forblanca** [comment]
already handle it.seems missing an 'export' in hanzi2num.js

**Comment by LingDong-** [comment]
Glad you already figured out. The newest code now has the `exports` added. It was due to a pull request which added tests to hanzi2num.js, which also accidentally removed the export lines.
Thanks for reporting it.
