### ISSUE TITLE
提个建议，古文是没有符号的，所以可以考虑简化一下符号，换成其他的做分割

### ISSUE THREAD

**Issue by liuhuo-qiu** [LingDong-/wenyan-lang#129]
提个建议，古文是没有符号的，所以可以考虑简化一下符号，换成其他的做分割，古文不同人读出不同的意思也是因为缺乏标点符号的原因，所以完全拟古文的话，建议把符号去除，换成空格或者其他的做分割

**Comment by xzcxzcyy** [comment]
文档里提到了，符号是可去除滴~

**Comment by yuesha-yc** [comment]
符号和空格是任意的

**Comment by Gcaufy** [comment]
用“兮”，“也”
吾有一数兮曰三也

**Comment by WinUP** [comment]
个人觉得，非关键字字符一律忽略就可以了，那样不管怎么插语气词都过得去。

**Comment by CeleritasCode** [comment]
对，书名号太难打了

**Comment by heangfat** [comment]
你所謂「符號」指何物？若指標點符號，則「『古文』无標點符號」是个常見的錯誤認知。
見此知乎答案:[「句读」有无明确的产生时间，产生于于何时，历史沿革怎样？](https://www.zhihu.com/question/24058969/answer/38202966)。可以看看《中國古代標點符號發展史》或《漢語標點符號流變史》。如欲自行探个究竟，還應多讀古籍 (包括出土簡、牘、帛等)。

**Comment by EndlessCheng** [comment]
![image](https://user-images.githubusercontent.com/7086966/71140756-2661ef00-224d-11ea-8706-075fa84fcf7e.png)

**Comment by lanten** [comment]
没有符号的大片中文字符，没有层次感，会导致阅读效率显著降低

**Comment by antfu** [comment]
Fixed in [v0.1.2](https://github.com/LingDong-/wenyan-lang/pull/416). Closing now. Feel free to reopen it if you got any questions.
