### ISSUE TITLE
Some number keywords in hanzi2num.js are not included in parser.js

### ISSUE THREAD

**Issue by carlyu99** [LingDong-/wenyan-lang#130]
Such keywords include `"纖","沙","恆河沙","阿僧祇","那由他","不可思議","無量大數","模糊","逡巡","須臾","瞬息","彈指","剎那","六德","虛","空","清","淨"`.

**Comment by farteryhr** [comment]
personally i think multi character units may be too useless, also 無量大數 may be better used to represent `Infinity`.
