### ISSUE TITLE
More complex while loops

### ISSUE THREAD

**Issue by Person314159** [LingDong-/wenyan-lang#135]
Currently there is only while (true). How might I write something like
```js
while (lst[index] != 0)
```
?

**Comment by LingDong-** [comment]
Hi there, currently you would put an `若`(if) statement within the loop to break out. The main reason for not making it into the `while(...)` line instead is that I think it would be equally verbose to describe what `while(...)` means in natural language.

If someone could think of a succinct and beautiful way to describe while(...). I would consider adding it. Thanks!
