### ISSUE TITLE
Try add render function to cmdline

### ISSUE THREAD

**Issue by Landau1994** [LingDong-/wenyan-lang#140]
I tried add render function to cmd line; it's work for me on windows
`function cmdlinecode(){
	var ARGS = [
		["--lang",    "-l", String,  "js",          "Language: js/py"],
		["--roman",   "-r", String,  "none",        "Romanize identifiers"],
		["--output",  "-o", String,  "/dev/stdout", "Output file"],
		["--exec",    "-x", Boolean, false,         "Execute ouput"],
		["--eval",    "-e", String,  "",            "Give a string instead of a file"],
		["--log",     null, String,  "/dev/null",   "Log file"],
		["--inspect", "-i", Boolean, false,         "Interactive REPL"],
		["--input",   null, String,  "/dev/null",   "input file"],
		["--render",  null, Boolean, false,         "render input"],
	]
	var ART = ` ,_ ,_\n \\/ ==\n /\\ []`
	function printhelp(){
		ARGS.sort()
		console.log(ART);
		console.log("\nWENYAN LANG 文言 Compiler 0.01 ("+compileinfo+")")
		console.log("\nUsage: wenyan [options] [input files]")
		console.log("\nOptions:")
		var ret = "";
		for (var i = 0; i < ARGS.length; i++){
			ret += ARGS[i][0].padEnd(9) + " "
			if (ARGS[i][1]){
				ret += ARGS[i][1] + " "
			}else{
				ret += "   "
			}
			ret += ("<"+(typeof ARGS[i][2]())+">").padEnd(9);
			ret += " : "
			var s = ARGS[i][4]+" (default: `"+ARGS[i][3]+"')"
			var n = 50
			if (s.length < n){
				ret += s
			}else{
				var l = s.split(" ");
				var m = Math.floor(l.length/2)
				var s0 = l.slice(0,m);
				var s1 = l.slice(m);
				ret += s0 + "\n" + " ".repeat(16)+s1
			}
			ret += "\n"
		}
		console.log(ret)
	}

	function argparse(){
		if (process.argv.length <= 2){
			printhelp()
			process.exit();
		}
		var args = {};
		for (var i = 0; i < ARGS.length; i++){
			args[ARGS[i][0]]=ARGS[i][3];
		}
		var files = [];
		var i = 2;
		while (i < process.argv.length){
			var a = process.argv[i];
			var b = process.argv[i+1];
			var found = false;
			for (var j = 0; j < ARGS.length; j++){
				if (a && (ARGS[j][0]==a || ARGS[j][1]==a)){
					args[ARGS[j][0]]=ARGS[j][2](b);
					i+=2;
					found = true;
					break;
				}
			}
			if (!found){
				if (a[0]=="-"&&(!a.includes("."))){
					console.log("Unrecognized argument: ",a);
					process.exit();
				}else{
					files.push(a);
					i+=1;
				}
			}
		}
		return {files,args};
	}
	function replscope(){
		function generate(depth){
			var s0 = "global.__scope=new function(){\n"
			var s1 = "\n}"
			for (var i = 0; i < depth; i++){
				var istr = "__"+(''+i).padStart(8,'0');
				s0 += `this.evil=function(${istr}){global.__scope=this;var __r=eval(${istr});\n`
				s1 = `;return __r}` + s1
			}
			return eval(s0+s1);
		}
		var stackCallSize = 1000;
		for (var i = stackCallSize; i > 0; i-=200){
		  try{
		    generate(i);
		    stackCallSize = i;
		    break;
		  }catch(e){
		    //console.log(i+ " exceeds max stack size");
		  }
		}
		// console.log("final stack size "+stackCallSize);
	}

	function repl(args){
		const readline = require('readline');
		const rl = readline.createInterface({
			input: process.stdin,
			output: process.stdout
		});
		global.haserr = false;
		rl.question('> ', (inp) => {
			var out = compile('js',
				inp,
				{
					romanizeIdentifiers:args['--roman'],
					logCallback:writer('/dev/null','a'),
					errorCallback:function(x){console.error(x);global.haserr = true},
				}
			)
			if (global.haserr){
				// console.log("Not evaulated.")
			}else{
				console.log("\x1b[2m"+out+"\x1b[0m")
				try{
					global.__scope.evil(out);
				}catch(e){
					console.log(e)
				}
			}
			rl.close();
			repl(args);
		});
	}

	function writer(f,mode){
		if (f == "/dev/null"){
			return ()=>0;
		}else if (f == "/dev/stdout"){
			return (x)=>((typeof x)=="string")?console.log(x):console.dir(x,{depth:null,'maxArrayLength':null});
		}else if (f == "/dev/stderr"){
			return console.error;
		}else if (mode == 'a'){
			return function(x){
				fs.appendFileSync(f,(((typeof x)=='object')?JSON.stringify(x):x.toString())+"\n");
			}
		}else if (mode == 'w'){
			return function(x){
				fs.writeFileSync(f,(((typeof x)=='object')?JSON.stringify(x):x.toString())+"\n");
			}
		}
	}

	function main(){
		var {files, args} = argparse();
		var scope_generated = false;
		var out = compile(args['--lang'],
			files.map(x=>
				x.endsWith('.svg')?
					 unrender([fs.readFileSync(x).toString()])
					:fs.readFileSync(x).toString()
				).join("\n")+"\n"+args['--eval'],
			{
				romanizeIdentifiers:args['--roman'],
				logCallback:writer(args["--log"],'a'),
				errorCallback:function(x){console.error(x);process.exit()},
			}
		)
		writer(args['--output'],'w')(out);
		if (args['--exec']){
			if (args['--lang'] == 'js'){
				if (!args['--inspect']){
					eval(out);
				}else{
					replscope();
					scope_generated = true;
					global.__scope.evil(out);
				}
			}else if (args['--lang'] == 'py'){
				var execSync = require('child_process').execSync;
				fs.writeFileSync("tmp.py",out);
				var ret = execSync("which python3; if [ $? == 0 ]; then python3 tmp.py; else python tmp.py; fi; rm tmp.py",{ encoding: 'utf-8' })
				console.log(ret);
			}
		}
		if (args['--render']) {
			var svgs = render("曼德博",fs.readFileSync(args['--input']).toString(),{plotResult:true})
			//console.log(unrender(svgs))
			for (var i = 0; i < svgs.length; i++){
				fs.writeFileSync(args['--output']+".svg",svgs[i])
			}
		}
		if (args['--inspect']){
			if (!scope_generated){
				replscope();
			}
			repl(args);
		}
		return 0;
	}

	main();
}`

**Comment by LingDong-** [comment]
Thanks, I've incorporated your code with some changes: 50d7f982a8920bb02f85621dd7c9afa0fb17ddd1

**Comment by antfu** [comment]
@LingDong- I am just planning to support rendering direct from the vscode extension. Thanks for that change!

But when we do the rendering, there will be two files generated (compiled js and the svg). Maybe we should make `render` outputs svg only?

For example
```bash
$ wenyan beer.wy --output .
# outputs beer.js
```

```bash
$ wenyan beer.wy --render --output .
# outputs beer.svg
```

**Comment by LingDong-** [comment]
Good suggestion! I just pushed: 7dd71b4ef2074aff9f89f8b0a140fd1266d2f8eb

Now if `--render <title-here>` is on, it will only output the svg. Otherwise it outputs `js/py` as specified by `--lang`.

I like the `.` syntax so I added that too.

`--render` needs to have an argument that is separate from input/output filename though, e.g. `--render 快排`, because I need that Chinese name to draw on the left and right edges of the rendered page.

Thanks for your great work

**Comment by antfu** [comment]
@LingDong- Should we add a syntax for declaring the title at the beginning of the file, and the --render argument can be optional.

Sorry, my Wenyan is not as good as others in this repo, I can not give a decent example. But something like this:
```
此乃「斐波那契演算法」篇。

吾有一術。名之曰「斐波那契」。欲行是術。必先得一數。曰「甲」。乃行是術曰。
	若「甲」等於零者乃得零也
	若「甲」等於一者乃得一也
	減「甲」以一。減「甲」以二。名之曰「乙」。曰「丙」。
	施「斐波那契」於「乙」。名之曰「丁」。
	施「斐波那契」於「丙」。名之曰「戊」。
	加「丁」以「戊」。名之曰「己」。
	乃得「己」。
是謂「斐波那契」之術也。

施「斐波那契」於十二。書之。
```

**Comment by LingDong-** [comment]
Sounds good. But now that I think more of it, it's probably easier to just use the output file name by default. People have the freedom to name their output file in Chinese. If they prefer ascii, they specify the argument to render. How does that sound?

**Comment by LingDong-** [comment]
Pushed the code for that idea. Now one can use `--render .` to use output filename for display name in the render.

**Comment by antfu** [comment]
Great! Rendering is also shipped in the latest version of the extension. Thanks for the great work!

**Comment by Landau1994** [comment]
It's my pleasure, thanks for your great work!
