### ISSUE TITLE
莊子 內篇 逍遙遊

### ISSUE THREAD

**Issue by calpa** [LingDong-/wenyan-lang#141]
I am wonder if this engine can parse 逍遙遊 as javascript code

北冥有魚，其名為鯤。鯤之大，不知其幾千里也。化而為鳥，其名為鵬。鵬之背，不知其幾千里也；怒而飛，其翼若垂天之雲。是鳥也，海運則將徙於南冥。南冥者，天池也。

=>
```
北冥.魚.name = 鯤
鯤.大 = 幾千里
鯤.化而為鳥 = function() {
  return 鵬;
}

鵬.背= 幾千里
```

**Comment by angle600** [comment]
化而为鸟，应该是一种类型转换。

**Comment by angle600** [comment]
魚是一個類，鳥也是一類
鯤、鵬是對象
化而為鳥是類型轉換
飛是鳥的方法

**Comment by angle600** [comment]
北冥是名字空間
魚是一個類，鳥也是一類
鯤、鵬是對象
化而為鳥是類型轉換
飛是鳥的方法

**Comment by angle600** [comment]
北冥是名字空間
魚是一個類，鳥也是一類
鯤、鵬是對象
化而為鳥是鳥類用對象鯤構造出其對象鵬
飛是鳥的方法

**Comment by angle600** [comment]
北冥是名字空間
魚是一個類，鳥也是一類
鯤、鵬是對象的引用
化而為鳥是魚有一個方法，用烏的構造方法，轉化為烏類的鵬
飛是鳥的方法

**Comment by pangh0ng** [comment]
哈哈庄子面向对象编程
