### ISSUE TITLE
Array.forEach一种实现

### ISSUE THREAD

**Issue by SilasFan** [LingDong-/wenyan-lang#145]
`皆「添一」于「众位」`

**Comment by LingDong-** [comment]
Hi, thanks for the suggestion.

Currently there is already a syntax analogous to `Array.forEach`, like so

```
凡「甲」中之「乙」
```

Or perhaps you're referring to `Array.prototype.map`, where 「添一」is the function? In that case I'm happy to put it on the todo list, perhaps along with other functional programming elements.

Thanks.

**Comment by calpa** [comment]
Actually, `凡「甲」中之「乙」` will render as `for (var 乙 of 甲) {`, so `Array.prototype.map` maybe missing in this engine.

**Comment by SilasFan** [comment]
Sorry for lack of definition for `「添一」`, which is thought to be predefined ahead as a normal function.
As for other fp elements, I may try to find appropriate implementations🤣🤣

**Comment by SilasFan** [comment]
Update: Make syntax closer to project's
Similarly, `「添一」` is predefined ahead, in JS might be:
```javascript
function addOne(x) {
    return x+1;
}
```
Impletements `Array.prototype.map` like:
`吾有 「甲列」者，  皆「添一」其上，皆 「添一」其上，终得 「乙列」也`

**Javascript:**
```javascript
var bList = aList.map(addOne).map(addOne);
```

In Addition, there's a possible implementation for `compose`:
`吾有一数，名之曰 「添五」, 盖合「添一」, 「添一」, 「添一」, 「添一」,  「添一」者也`
(The parser translate `吾有一术` to keyword `function`, so I use `吾有一数`)

**Javascript:**
```javascript
var addFive = compose(addOne, addOne, addOne, addOne, addOne)
```

If functions in `compose` need params, can expand to:
`吾有一数，名之曰 「添二」, 盖合「添」于「一」, 「添」于「一」者也`
（But I forget whether the syntax is available in Traditional Chinese🤣🤣）
