### ISSUE TITLE
可有运行时解析器可用否？~

### ISSUE THREAD

**Issue by sunwanxin213** [LingDong-/wenyan-lang#158]
仅需转译为 JavaScript ，输入string，输出string（JavaScript）即可。
可有计划？

**Comment by antfu** [comment]
没记错的话 Online IDE 已经有了

**Comment by sunwanxin213** [comment]
Online IDE不等于公开API啊。。。

**Comment by antfu** [comment]
You can use @wanyanlang/core package now. The detail API specification is on the way. You can try to read the src/parser.js before that.
