### ISSUE TITLE
求一个vscode扩展

### ISSUE THREAD

**Issue by lixinyang123** [LingDong-/wenyan-lang#16]
如题

**Comment by antfu** [comment]
刚刚摸了一个 https://github.com/antfu/wenyan-lang-vscode 🌝

**Comment by lixinyang123** [comment]
哇，感谢大佬

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Anthony Fu <notifications@github.com>
发送时间: Wednesday, December 18, 2019 1:36:40 AM
收件人: LingDong-/wenyan-lang <wenyan-lang@noreply.github.com>
抄送: LLLXY <lixinyangemil@outlook.com>; Author <author@noreply.github.com>
主题: Re: [LingDong-/wenyan-lang] 求一个vscode扩展 (#16)


刚刚摸了一个 https://github.com/antfu/wenyan-lang-vscode 🌝

**Comment by LingDong-** [comment]
Thanks a lot @antfu ! I've put a link to it in the README. (57acbfe66147b2d174023c285ee5c473aa44a047)
