### ISSUE TITLE
Modifying Elements in Arrays

### ISSUE THREAD

**Issue by danielz02** [LingDong-/wenyan-lang#162]
Is there a way to modify a certain element in the array by index?
```
夫「甲」之「戊」。曰「後」。
```
This won't assign `「後」` to `甲[戊]`.

**Comment by godwings** [comment]
```
吾有一列。名之曰「甲」。充「甲」以四。以二。
吾有一數。曰一。名之曰「乙」。
昔之「甲」之「乙」者。今「乙」是矣。
吾有一列。曰「甲」。書之。
```
This can assign 「乙」 to 甲「乙」

**Comment by danielz02** [comment]
> ```
> 吾有一列。名之曰「甲」。充「甲」以四。以二。
> 吾有一數。曰一。名之曰「乙」。
> 昔之「甲」之「乙」者。今「乙」是矣。
> 吾有一列。曰「甲」。書之。
> ```
> 
> This can assign 「乙」 to 甲「乙」

Thanks!

**Comment by cuixiping** [comment]
> ```
> 吾有一列。名之曰「甲」。充「甲」以四。以二。
> 吾有一數。曰一。名之曰「乙」。
> 昔之「甲」之「乙」者。今「乙」是矣。
> 吾有一列。曰「甲」。書之。
> ```

The last line should be 
```
夫「甲」。書之。
```
