### ISSUE TITLE
如何把取模结果赋值给变量？

### ISSUE THREAD

**Issue by sqrt81** [LingDong-/wenyan-lang#172]
> 除十以六，所餘幾何。昔之「甲之餘」者。今其是矣。

结果：「甲之餘」＝10/6。
如何实现「甲之餘」=10%6这个语句？

When I run

> 除十以六，所餘幾何。昔之「甲之餘」者。今其是矣。

I got 「甲之餘」＝10/6.
So how can I assign 10%6 to 「甲之餘」?

**Comment by LingDong-** [comment]
Currently commas `，` are not supported, it's causing the parser to misunderstand the line

Please use

```
除十以六。所餘幾何。
```

which compiles to

```
var _ans1 = 10 % 6;
```

I agree that more helpful error messages are in need ;)

Thank you for bringing this up.

**Comment by sqrt81** [comment]
Thanks! It works when I change  ， into 。.
