### ISSUE TITLE
Missing Statement in if Child

### ISSUE THREAD

**Issue by danielz02** [LingDong-/wenyan-lang#176]
I have the following if statement.
```
若「後」大於「前」者。
    昔之「甲」之「戊」者。今「後」。
    昔之「甲」之「己」者。今「前」。
若非乃止也。
```
However, this is the translated JavaScript code.
```
if (後 > 前) {
    甲[戊 - 1] = 後;
} else {
    break;
};
```
It seems that the second statement in the if child is missing.

**Comment by LingDong-** [comment]
Hi there, you're missing `是矣`. Please use:

```
若「後」大於「前」者。
    昔之「甲」之「戊」者。今「後」是矣。
    昔之「甲」之「己」者。今「前」是矣。
若非乃止也。
```

I'll make a better documentation and better error messages. Hopefully those will make things clearer. Thanks for bringing it up.

**Comment by danielz02** [comment]
> Hi there, you're missing `是矣`. Please use:
> 
> ```
> 若「後」大於「前」者。
>     昔之「甲」之「戊」者。今「後」是矣。
>     昔之「甲」之「己」者。今「前」是矣。
> 若非乃止也。
> ```
> 
> I'll make a better documentation and better error messages. Hopefully those will make things clearer. Thanks for bringing it up.

Thanks! Better documentation and error message will be very helpful! Also, the `wenyan.js` will freeze when there's some sort of syntax error.
