### ISSUE TITLE
吾有一數。曰九億七千二百七十四萬四千九百六十四。名之曰「扣扣群」。

### ISSUE THREAD

**Issue by masterKPr** [LingDong-/wenyan-lang#18]
吾有一數。曰九億七千二百七十四萬四千九百六十四。名之曰「扣扣群」。
欲以每日斗「欧拉」。

**Comment by Jaggle** [comment]
should be removed as spam contents😓

**Comment by masterKPr** [comment]
> should be removed as spam contents😓

Relax, this is not spam
