### ISSUE TITLE
How to type "「" on Windows 10 with Microsoft Pinyin

### ISSUE THREAD

**Issue by zhmushan** [LingDong-/wenyan-lang#19]

**Comment by LingDong-** [comment]
I heard you can type unicode on windows by doing a key combo of `alt` and `+` and the unicode entry point. I don't have a windows computer at hand so please see [this wikipedia article for details](https://en.wikipedia.org/wiki/Unicode_input). The unicode entry points for `「」` are `300C` and `300D`. 

For macs users, it would simply be `shift`+`[` or `]`.

Perhaps I'll add a pair of buttons on the online IDE to facilitate typing these symbols. Thanks for bringing it up.

**Comment by antfu** [comment]
If you are using VSCode, you can try [this extension for Wenyan](https://github.com/antfu/wenyan-lang-vscode).

It will replace punctuations automatically as you type.

![](https://github.com/antfu/wenyan-lang-vscode/raw/master/screenshots/demo-punctuations.gif)

**Comment by zhmushan** [comment]
@LingDong- @antfu Thx reply!
