### ISSUE TITLE
吾有一言，请诸位静听

### ISSUE THREAD

**Issue by usbcdrom** [LingDong-/wenyan-lang#204]
吾有一言，请诸位静听

**Comment by BenjaminWbj** [comment]
住口，无耻老贼。

**Comment by fangchunzao** [comment]
汝甚屌  家知否

**Comment by CharlesKan** [comment]
但说无妨

**Comment by usbcdrom** [comment]
昔日桓帝、灵帝之时
，汉统衰落，宦官酿祸，国乱岁凶，四方扰攘。
，黄巾之后，董卓，李榷，郭汜等接踵而起。劫持汉帝，残暴生灵，因之，庙堂之上，朽木为官；殿陛之间，QIN SHOU食禄。以至狼心狗肺之辈汹汹当朝，奴颜婢膝之徒纷纷秉政，以致社稷变为丘墟，苍生饱受涂炭之苦！
值此国难之际，正是吾辈报效国家之时。
东吴孙氏，世食汉禄，理应框君辅国，报效国家。何期勾结曹魏，反叛朝廷，同谋篡位，罪孽深重，天地不容。

今幸天命不绝炎汉，我昭烈皇帝于西川继承大统。带领西川三军兴师讨贼，誓灭东吴，以谢天下。
