### ISSUE TITLE
建议作者 Close 一些无意义的 Issue

### ISSUE THREAD

**Issue by rikakomoe** [LingDong-/wenyan-lang#208]
建议作者 close 并 lock 掉纯属发表个人评论而没有的建设性 issue，现在 issue 太多，找关于文言的建议和提案的 issue 太难找。

**Comment by antfu** [comment]
It's also good to add a bot that closes invalid issue automatically.

**Comment by kotritrona** [comment]
https://kotritrona.github.io/postbar/bar.html?kw=LingDong-%2Fwenyan-lang

**Comment by melop** [comment]
嗚呼，此帖須關矣。

**Comment by LingDong-** [comment]
I was hoping people would realize that their posts are not constructive, and close them themselves.  But I can see that's not happening :P I'll look into the bots.
Thanks

**Comment by ExerciseBook** [comment]
惨 ao 惨

Refer to my experience, issues list will turn into bbs sometimes. 😂

**Comment by UltimatePea** [comment]
An issue guideline (i.e. .github/issue.md) would also help.

**Comment by rikakomoe** [comment]
@LingDong- 
> I was hoping people would realize that their posts are not constructive, and close them themselves.

就像你说的， that's not happening. 事实上新开的 issue 的速度远远比 close 的多，所以现在 issue 区已经充斥着没用的 issue。如果不考虑开发的话当个论坛倒也没问题，主要是和 wenyan-lang 提案相关的那些 issue 越来越难找了，除非把建设性的讨论另挪他处，否则就需要积极关闭 issue。

close 并 lock issue 还可以鼓励更多人参与进来。现在这个情况一般人不敢 watch，一旦 watch 邮箱就会被打爆。而相反现在 issue 区各种 666 和撕逼则鼓励了人们开新 issue 来发表自己的看法，如果 issue 区非常整洁我觉得这种行为也会减少。

> I'll look into the bots.

据我所知，我见过的 bot 唯一的功能都是如果不按照 issue 模板发帖，就立即关闭 issue。bot 并不能真正有效地过滤 spam。最后还是需要维护者来做这项工作。但这个工作量也没有想象的大，只要积极地清理，很快就能让这里回归秩序（notepad++ 被机器人刷版几千条也很快就清理完了）

**Comment by rikakomoe** [comment]
@ExerciseBook 
> Refer to my experience, issues list will turn into bbs sometimes. joy

这个其实本不必发生在这里。因为你看 @LingDong- 每个 issue 都回复，只要他在浏览 issue 的时候随手点个 close 和 lock 就行了 :)

我相信 @LingDong- 如果现在还在回复 issue 的话一定也很受困扰，因为 spam 太多找一个要回复的 thread 要翻好多页，真的很难找。

如果需要协助的话我可以帮忙。

**Comment by LingDong-** [comment]
Hi everyone,

I manually closed all the irrelevant posts.

If your issue is closed, please don't take it personally.

For future issues: If you feel like complementing my work, thank you, but there is no need to open an issue, simply give me a star or tell your friend about it. If you feel like criticizing me, please use these two dedicated threads to do so: #174 #177

Thanks!
