### ISSUE TITLE
More traditional typeface (classical standard) in rendered SVG

### ISSUE THREAD

**Issue by edward-martyr** [LingDong-/wenyan-lang#213]
Right now the rendered SVGs use [新字形](https://zh.wikipedia.org/wiki/%E6%96%B0%E5%AD%97%E5%BD%A2), a Ming type standard derived from handwritten Kai. However, this mainland standard does not reflect how types were done in dynastic times or even in Taiwan (which, even then has gone through modernisations, e.g. 青 vs 靑, 為 vs 爲). 

Using traditional Ming types will best reflect the vertical typography of Middle Chinese, so please consider using a good 舊字形 typeface (e.g., use a well-forged one such as [一點明朝](https://github.com/ichitenfont/I.Ming) to avoid the amateur-made) to render SVGs.

Here's a demonstration (I've put a dot right to each problematic form):
左：一點明朝；中：Noto Serif CJK KR；右：Noto Serif CJK TC。
<img width="279" alt="Screenshot 2019-12-19 at 18 27 28" src="https://user-images.githubusercontent.com/42882301/71166238-3b5e7280-228d-11ea-95d8-ac4a360eaf9d.png">
As you can see, even the Taiwanese traditional Chinese (TC) standard is inconsistent at times.

**Comment by LingDong-** [comment]
I see! Thanks a lot for pointing that out. I do think it's important to use an authentic typeface.

However, to my knowledge, SVG does not embed font inside its files, so so what shows up depends on what fonts are installed on the user's system. What I can do is to specify the name of the desirable font (e.g.一點明朝) in the SVG, and ask users to install that font on their system.

Please feel free to contradict me with SVG tricks that I'm not aware of!

**Comment by hfhchan** [comment]
SVG allows font embedding but the svg file generated would be impossible large (>20MB).  I just made a pull request for font fallback instead.
