### ISSUE TITLE
除了映射之外 还有什么？？ 单纯的冗余？？

### ISSUE THREAD

**Issue by willshion** [LingDong-/wenyan-lang#228]
一大堆的吾。。 书之。。？

**Comment by willshion** [comment]
能拿风投吗 烂钱我也想恰。。

**Comment by Saafo** [comment]
别人写个期末作业而已.....

**Comment by fkysly** [comment]
> 一大堆的吾。。 书之。。？

觉得简单的话，你也写一个呗。

**Comment by phabeler** [comment]
此言差矣。有趣不就夠了嗎^^

**Comment by ExerciseBook** [comment]
讲道理，一个大作业可以整个上万star岂不美哉？

**Comment by Saafo** [comment]
@ExerciseBook 美哉美哉，可有一说一技术上虽然不难，别人是真的有创意

**Comment by xl70** [comment]
这只是个大三学生搞出来的兴趣项目，非得上纲上线么。这样的练习对一个有创意的程序员的炼成是很有价值的。

**Comment by Saafo** [comment]
@xl70 赞同，btw我看csdn报道的是大四的学生....又查了一下是CMU的学生，不得不说还是挺强的，这样的课设真的太棒了

**Comment by LingDong-** [comment]
Just to clarify, this is not a homework. It's a personal project ;)
