### ISSUE TITLE
How can it interact with other programming languages?

### ISSUE THREAD

**Issue by AshyAzure** [LingDong-/wenyan-lang#232]
突然想到一個問題，在這門語言成熟之後，如果完全只接受文言的話，那它怎麼和其他程序交互呢？（比如JSON？
Coming up with a question: if this language only accept Classical Chinese as its identifiers, how can it interact with other programs? (via JSON for example?

但是別的程序應該都是用英文的吧，這樣代碼裡總不免要帶上英文的。
However, other programs will use English (in JSON), making English usage inevitable.

是否有必要適當加入對英文變量名的支持？

**Comment by LingDong-** [comment]
Hi, thanks for your proposal.
English variable names are allowed. In fact, since all identifiers are enclosed with `「」`, you can put just about anything unicode in there. It's just that using Chinese variable names are encouraged, if possible.
