### ISSUE TITLE
An Error In wenyan-lang

### ISSUE THREAD

**Issue by RyuGamer** [LingDong-/wenyan-lang#24]
There's a slight error here that the number 「二百五」 will be mistaken for 205, which should be 250.

**Comment by LingDong-** [comment]
Oops! I will fix that. Thanks for spotting it

**Comment by LingDong-** [comment]
This bug should be fixed now. ffca311ca5db9cc60985c49097439ddaf0ee1a03
The solution is not as beautiful as I would like, so I'll look into it again when I have time.
