### ISSUE TITLE
吾求BNF

### ISSUE THREAD

**Issue by KimotoYanke** [LingDong-/wenyan-lang#255]
I'm making a [Kundoku](https://zh.wikipedia.org/wiki/漢文訓讀) Generator for Wenyan, but the parser doesn't keep the hanzi information like difference between "吾有" and "今有". So I want to try to make a parser for Kundoku but the documentation are scattered. Is there BNF like syntax description?

**Comment by LingDong-** [comment]
Hi, there is a rough and incomplete BNF draft we're working on in `./documentation/syntax.txt`. We will announce it once it is finished! Thanks so much for your interest in this project, looking forward to your Kundoku Generator!

**Comment by GalAster** [comment]
这里有:

https://github.com/LingDong-/wenyan-lang/blob/master/documentation/syntax.txt

我准备用  ANTLR 重构一遍, 然后兼容全角半角, 还有繁体简体

https://github.com/GalAster/WenyanLanguage/blob/master/packages/wenyan-parser/Wenyan.g4

**Comment by rockswang** [comment]
@GalAster 赞，这算是步入正轨了，另外我觉得编译器后端可以直接生成estree，然后再用astring，或者[espy](https://github.com/KodyJKing/espy) 转译成js和python即可

**Comment by KimotoYanke** [comment]
Thank you for telling me!

**Comment by rockswang** [comment]
有点意思，这位是日本人吧，要在文言上加假名训读，这渲染成图B格那是相当高啊
