### ISSUE TITLE
史上最烂编程语言！

### ISSUE THREAD

**Issue by hzqd** [LingDong-/wenyan-lang#261]
1. 特性过简效率低下、关键词累赘繁琐、表达既模糊又冗余，这样的语言根本不应该称为编程语言！

2. 这个项目是用JavaScript写的，而JavaScript本身就是垃圾中的垃圾。使用垃圾工具来写项目，那这个项目往往会受到该工具作者根深蒂固的思维局限性，导致无法自拔的痛苦。

3. 编译器会把你的文言代码编译到 JavaScript、Python、Ruby 等一众民科外行发明出来的糟粕，未来还可能支持编译到C语言这种过时落后的老古董。其眼界和水平可想而知。

4. 这个语言毫无设计可言，就更别谈用户体验了。中文，而且还是文言文，竟然能比英文长，真乃历史奇观耶！

5. 如果说Java和Haskell这样的语言还值得批评的话，那对上述这些语言的设计者只能说：去补补课吧！别再以丑为美了！也别再制作糟粕来祸害软件工程和计算机科学的世界了！

**Comment by AshyAzure** [comment]
Here is an issue to be closed

**Comment by guxd** [comment]
嫌不好可以别用，或者加入一同改进。喷子gun粗。

**Comment by Leibosite** [comment]
请亮出你的设计，总觉得你写的12345条，那你应该是一个让人膜拜的大师，千万别深藏功名尘与土。

**Comment by SnowOnion** [comment]
垠持，，，

**Comment by jingyuexing** [comment]
* 有人夸你别信，有人骂你别听。
* 活100岁能有几个人，**开心就笑，不开心待会儿再笑**。高高兴兴比什么都强，跟谁较劲都是跟自己较劲。一辈子，忍忍就过去了
* 人生在世，谁都会吃屎，但别嚼。跟狗抢道，让狗先过，不丢人。
-----郭德纲

**Comment by Cyvadra** [comment]
C语言这种过时落后的老古董？？？？？？你怕不是写python的吧？

**Comment by l-iberty** [comment]
真正学计算机的人不会说出这种话，因为真正学过计算机的人知道现代操作系统如windows,linux内核都是用C语言写的，甚至tensorflow这种东西底层都是C实现的。我不歧视任何一门语言，但歧视那些歧视某些语言的人，特别是当他说出他歧视C语言这种话，我就知道这个人绝对不是学过计算机的，只是一个傻逼

**Comment by jingyuexing** [comment]
哪个人前不说人,哪个人后不被说。一个语言又不是钞票，还能让人人都喜欢？
用语言诟病之处来推脱自己的垃圾，人人都会有这个时候，人生漫漫，跟个傻逼堵心眼字干嘛

**Comment by yindaheng98** [comment]
才9repo的🌶🐔也ge这🚿来？给👨爬

**Comment by PEDx** [comment]
又是一个教条主义者, 喷出来是否显得自己很有力量?  无聊, 毫无幽默感, 搞半天有些人还认真了. 编程语言只分两种, 一种没人用另一种被人骂.

**Comment by gotSomeCool** [comment]
javascript是垃圾中的垃圾。。。。。。你说是那就是，行吧

**Comment by lvkk77** [comment]
you can you up,no can no BB

**Comment by charliezzo** [comment]
JavaScript、Python、Ruby 等一众民科外行发明出来的糟粕……
如果这个世界上有一个人能说这句话，他是 Linus Torvalds 或是 Dennis MacAlistair Ritchie
楼主目前还不能
语言没有好坏，只有适合不适合

**Comment by wenjunyang** [comment]
垠

**Comment by XUEBOKIVI** [comment]
脑残吧。你要是觉得不好，就自己做个更有意思的。作者完全是出于兴趣搞得，你在这里唧唧歪歪。智障一个

**Comment by paulyung541** [comment]
楼主喷子一个，完全讲不出理由，纯喷
这种傻逼别侮辱了计算机这个行业

**Comment by shiguangpaoqini** [comment]
你白银说是我辣鸡，那就是我辣鸡，为什么你们知道吗，因为白银这个段位很尴尬，白银说的话就像是一位癌症晚期患者说的话。他都已经这样了,你为什么不顺从他，你总得给人留一段美好的回忆吧，最后的时光里。

**Comment by rolevax** [comment]
钓鱼耳

**Comment by FrankHB** [comment]
短的[倒是不难](https://github.com/audreyt/lingua-sinica-perlyuyan/blob/master/lib/Lingua/Sinica/PerlYuYan.pm)，就怕少见多怪……

不过讲道理，要发明“最烂”，这里的人大概是没这个本事的。

**Comment by bxpxqxd** [comment]
> C语言这种过时落后的老古董？？？？？？你怕不是写python的吧？

他说 JavaScript、Python、Ruby 等是一众民科外行发明出来的糟粕，可能这一众里还包含 PHP、Swift、Kotlin，而说 C 是老古董，那他可能是写 C# 的

**Comment by FrankHB** [comment]
行吧，咬钩娱乐……

我寻思一门语言都不知道辣鸡在哪的用户，居然还有脸装熟？奇怪哉也。一抓一把 C 的云用户石锤了……

> 真正学计算机的人不会说出这种话，因为真正学过计算机的人知道现代操作系统如windows,linux内核都是用C语言写的，甚至tensorflow这种东西底层都是C实现的。我不歧视任何一门语言，但歧视那些歧视某些语言的人，特别是当他说出他歧视C语言这种话，我就知道这个人绝对不是学过计算机的，只是一个傻逼

这可真是尬……不说这楼里能枚举出来的“现代操作系统”有多屑，Tensorflow 何德何能“甚至”？

（犹记当年糊微码闲下来倒腾 victim cache 的时候可真是憋气花了些时间骂死皮赖脸哈佛架构的无用功……真抱歉，真没用 C 在写，想到用 C 的场景，甚至还有点想笑……）

不说现在该咋婊 ALGOL 不肖子孙了，还是当有一句 mmp 要讲：这里的用户的 C 水平大概都是辣鸡（撑死也不会到连个有点卵用的 strict conforming program 都糊不出来的程度）——这大概是没翻案的可能性了。

当然这边反正也没 WG14 的人，骂不骂都是随便，反正非得糊 K&R 古董张口现代的，横竖也是打不醒的……（要是 WG21 我就直接 A 上去了）。

> 他说 JavaScript、Python、Ruby 等是一众民科外行发明出来的糟粕，可能这一众里还包含 PHP、Swift、Kotlin，而说 C 是老古董，那他可能是写 C# 的

自己会糊语言的，这些具体辣鸡也就是常识……（各种笑话不断，在 LtU 哪的也没见过给这些翻案的。）

不过这样废话确实没啥意义，还是找些小众点的乐子乐呵乐呵有点意思，比如[这个](http://www.atalon.cz/rb-om/ruby-object-model/)。

**Comment by 6ZILIULIU** [comment]
还c呐，你咋不用汇编，咋不回用纯电路呢，喜欢搞歧视？

**Comment by BinZhiZhu** [comment]
你他🐴是真的秀 张口就来 指挥家你好

**Comment by AAChartModel** [comment]
让脑残也获得了使用文字, 组织语言, 开启 GitHub issue 的能力,不知是这个世界的幸运还是不幸

**Comment by Lucifer1993** [comment]
He is right, This is not a useful language, it's difficult and crash.

**Comment by hustcc** [comment]
对喷子都适用。

https://github.com/LingDong-/wenyan-lang/issues/174#issuecomment-567329087

**Comment by Mcnwork2018** [comment]
你真的好酸啊

**Comment by riiyn** [comment]
不知这位大佬用的何种神仙语言啊

**Comment by Anduin2017** [comment]
评价语言好坏的标准，

* 不是关键字数量
* 不是是否接近底层
* 不是是否和JavaScript有关

你之前建立的一些理解完全是错的，可能需要对计算机的基础进行重新学习。

**Comment by tt67wq** [comment]
——————/´﻿ ¯/)
—————--/—-/
—————-/—-/
———--/´¯/'--'/´¯`·_
———-/'/--/—-/—--/¨¯
——--('(———- ¯~/'--')
———\————-'—--/
———-''————_-·´
————\———--(
————-\———-- ~~~

**Comment by jacktsui** [comment]
就一条：付诸实践本身就很伟大，想一想等于没想。

**Comment by mqhe2007** [comment]
我看你就是个垃圾，没错，我就是要人身攻击。

**Comment by Yamyee** [comment]
这人真不是反串？

**Comment by edmundwsy** [comment]
欲显尔

**Comment by frederick-vs-ja** [comment]
> He is right, This is not a useful language, it's difficult and crash.

It's just a toy and hence shouldn't be required to be as useful as some industrial languages.

**Comment by iwoeruhsdfwoi** [comment]
虽然没用但却是个艺术品。有这文言文功底和文采的程序员不多。
学完编译活学活用设计了一门简单的语言实现了语法分析和翻译，做得挺好。

**Comment by hzqd** [comment]
这是一场小型调查实验，我已经得到了我想要的东西，感谢每一位参与者！

**Comment by hzqd** [comment]
这是一场小型调查实验，我已经得到了我想要的东西，感谢每一位参与者！

**Comment by jingyuexing** [comment]
>这是一场小型调查实验，我已经得到了我想要的东西，感谢每一位参与者！
这是什么意思呢

**Comment by jingyuexing** [comment]
>这是一场小型调查实验，我已经得到了我想要的东西，感谢每一位参与者！

这是什么意思呢

**Comment by FrankHB** [comment]
> 
> 
> > He is right, This is not a useful language, it's difficult and crash.
> 
> It's just a toy and hence shouldn't be required to be as useful as some industrial languages.

I don't want to be harsh or rude, sincerely, but being esoteric is not interesting by itself. It is not interesting to me, even as a toy (as there have been prior arts in some degrees). I see no new interesting topics about ancient Chinese here, either. And there comes [APL stuff](https://github.com/LingDong-/wenyan-lang/issues/237)... That's _not even wrong_, besides the lack of a clear outline of the purpose of the toy. (It may or may not interesting than some "industrial languages", though.)

That said, I still agree with this comment. Moreover, comments among issues are actually far more interesting to me.
