### ISSUE TITLE
“吾有三數，”  黨結尾為逗號時初始化錯誤

### ISSUE THREAD

**Issue by zxch3n** [LingDong-/wenyan-lang#264]
```
吾有三數，曰「一」。曰「二」。曰「三」
```

=>

```
var _ans0 = 0;
var _ans1 = 0;
var _ans2 = 0;
```

在example/pi_leibniz.wy 中有出現該用法。

https://github.com/LingDong-/wenyan-lang/blob/15b9c9d5630406501789ca793ddcbffa83d17382/examples/pi_leibniz.wy#L5

**Comment by LingDong-** [comment]
Hi, commas are not supported yet, the one you spotted in `pi_leibniz.wy` must have been a typo. I'll correct that. Thanks!

**Comment by antfu** [comment]
The typo seems to be fixed. Closing now. If you got any questions, free feel to reopen it.
