### ISSUE TITLE
列index没对应上

### ISSUE THREAD

**Issue by hugeSaltFish** [LingDong-/wenyan-lang#27]
列的“充” 与 夫 列 之xx。index没有对应上 。充没有-1但是夫列之xx-1了

**Comment by ExerciseBook** [comment]
我感觉这个是故意的啦。
数组从一开始数。

**Comment by hugeSaltFish** [comment]
怎么数都应该对应上不是吗
不然
充列之一放进去之后
夫列之一拿不到充进去的东西啊

**Comment by ExerciseBook** [comment]
充不是 .push 嘛？

**Comment by LingDong-** [comment]
Hi @hugeSaltFish,

@ExerciseBook is correct, the syntax to push to an array and retrieve the first element is:

```
吾有一列。名之曰「甲」。充「甲」以四十二。
夫「甲」之一。書之。
```

compiles to:

```
var JIA3 = [];
JIA3.push(42);
var _ans35 = JIA3[1 - 1];
console.log(_ans35);
```

Outputs:

```
四十二
```

As I mentioned in other Issues, I will write a language spec to make these less confusing. Keep tuned!

Thanks.

**Comment by hugeSaltFish** [comment]
原来是push啊
JIA3.push(4, 2);
我大概是看成put了然后那边k-v对应，怎么想都对不上（扇子笑
好了没事了（扇子笑
