### ISSUE TITLE
可否将该项目的解析器部分传 npm 上

### ISSUE THREAD

**Issue by langyo** [LingDong-/wenyan-lang#274]
我已经开始着手写一份新的 ide 了，但首要问题是我得能够调用这个项目的核心

git submodule 方案我考虑过，但既然是一个能用的编译器，为何不能像 babel 等那样传 npm 上呢？

更进一步的需求是，最好别直接传一整个项目同在一份 npm 仓库中，可以像 babel 那样分一下(具体怎么回事，看 babel 源码你们就能懂了)

个人考虑可以传的 npm 库如下:
- wenyan-lang，对应于 src/parser（ #241 ）
- wenyan-render，对应于 src/render

如果能传 npm，我接下来写的 ide 的项目结构就能不那么尴尬了，并且也能因此，这个项目可以被作为命令行工具使用，岂不美哉？

请考虑下我的意见，谢谢！ @LingDong-

**Comment by langyo** [comment]
Oh，实在抱歉，我刚刚才看到 #241 ，这 issue 提重复了

不过分子包的建议仍然保留，就当是给 npm 包的上传提进一步的建议吧

（恕我没 international，比起英语，我更愿意用汉语表达我的想法……

**Comment by antfu** [comment]
We are publishing to npm now. For more details, please refer to https://github.com/LingDong-/wenyan-lang/blob/master/documentation/Compiler-API.md. Thanks.

Closing now. If you got any questions, free feel to reopen it.
