### ISSUE TITLE
不须掉书袋。科学还是正途。

### ISSUE THREAD

**Issue by PaulCnth** [LingDong-/wenyan-lang#291]
前几天就看到这个项目。一读而过。
觉得是一个有趣的尝试，但是，不应过度沉浸。

意大利在文艺复兴，有但丁一派人，改良语言，通俗易懂，拉丁文逐渐式微。
民国时，有鲁迅，胡适一派人，提倡白话，简洁明了，“不须放屁”【伟大领袖语】。

我们古代，读书人孜孜不倦，考究文字出处，钻在故纸堆中，终此一生。
浪费了年轻人大好时光，搞数学的少，搞化学物理天文的少，搞科研实验的少。
**科学，仍然是我们所能领先于世界的利器。**

钻故纸堆中翻翻捡捡，未尝不可。
只是别成了“掉书袋”。

文言，是一种**兴趣，文艺，欣赏**；
就好比，别人都在用新版圣经祷告，
而有些教徒，坚持拉丁经文一样。

各自安好。
但，**作为一个方向，拟或潮流，非常不赞同**。

**Comment by LGYcurry** [comment]
所言甚是，哈哈哈

**Comment by MrHikari** [comment]
古文，打个比方就是吸满墨水的海绵，你能从小小的一块挤出大量的意义。

**Comment by guxd** [comment]
文言跟科学相悖吗？用文言就不是正途，就是否定科学吗？ 
你这说法似乎跟当年相信汉字阻碍计算机发展的如出一辙。
觉得文言繁琐，是因为从小没有相关的阅读训练用不习惯。
外国人也觉得汉语繁琐，看着跟天书似的符号以为中国人都在痛苦的“掉书袋”。

**Comment by ijacksonliu** [comment]
这个当然是主要是欣赏作用，生活中不能总是代码，逻辑，算法。也要有诗和远方

**Comment by heangfat** [comment]
> 民国时，有鲁迅，胡适一派人，提倡白话，简洁明了

新文化運動大體是一場鬧劇。其罪大惡極之處，便是迫使中國文化退出實用領域，發展停滯，淪爲了你所謂之「興趣、文埶、欣賞」，不復日新。

**Comment by PaulCnth** [comment]
先帝说："汉贼不两立，王业不偏安"。誓破曹贼，迁于旧都。还回的去吗？

**Comment by PaulCnth** [comment]
我们希望更多的是一种兴趣，一种爱好，而非一种趋势。
**毕竟，通俗易懂，易于传播，才能把优秀的知识，从少数人传播到多数人**。

**Comment by AshyAzure** [comment]
emmm 你确定故纸堆是因为文言而不是文字狱？
宋代的科学研究还世界第一呢

**Comment by AshyAzure** [comment]
在敲定wenyan-lang之前确实是会去故纸堆里面翻东西，但是这是为了一个更加完善并且有趣的语法结构。
不然难道凭空造一个Esperanto2 ？
毕竟是几千年天生地养之物，我不信凭空造一门 Esperanto 出来会比它好用

**Comment by PaulCnth** [comment]
@AshyAzure “宋代的科学研究世界第一”，是否如此，且不说。南宋的哲学，理学，集大成，研究深度，确实不一般。
所以，**为了普通人都能听的懂大师的言论**，
他们借鉴了**佛经的语录体**，用尽量**浅显的话，比喻手法，讲给自己的学生听**。
这从《朱子语录》《二程遗书》，甚至明代的《传习录》上，
大体可窥一斑。

**知识，我们是要传授给学生，后人的，不是私藏的，**
子曰：“因材施教”，
学生天资各不同，得照顾到大多数人，
唯有浅显，方能孚众。

**Comment by guofei9987** [comment]
好玩就完事了

Why so serious?
