### ISSUE TITLE
通俗易懂，把知识从少数人的特权，传播给多数人。而非反之。

### ISSUE THREAD

**Issue by PaulCnth** [LingDong-/wenyan-lang#310]
文言在书面语，普及推广上，都更为小众。
读书人以博闻强识，自居于人，无可厚非。

但是，
试图把一些知识，变为**少数人的特权**，
让普罗大众当**愚民**的做法，
甚为不妥。

**白话，把知识的特权，从少数人手中夺回来。**

**倒行逆施，不知其可！**

**Comment by frederick-vs-ja** [comment]
这不算特权。因为现在有充分的条件学习文言文，甚至中国的九年义务教育里就有一些基础。

如果你觉得文法上的困难会“把知识编程少数人的特权”，那么你也可以考虑下给 C++ 标准委员会提建议，尽量把文法简化掉。

**Comment by PaulCnth** [comment]
所以，大家可以看到，因为Python语法的便捷性，
当然，最重要的，还有积累的各个领域优秀的库，
吸引了为数众多的各行业的普通人，参与到Python的使用当中。
这个，对于流行，普及，很有裨益。

**Comment by AshyAzure** [comment]
不可脱离特定的历史时期谈问题，白话确实带来大众知识普及，但是更多是为了反对清末的文章方式。胡适最开始提出白话是在：《文学改良刍议》：
```
一曰，须言之有物。
二曰，不摹仿古人。
三曰，须讲求文法。
四曰，不作无病之呻吟。
五曰，务去滥调套语。
六曰，不用典。
七曰，不讲对仗。
八曰，不避俗字俗语。
```
都只是针对文章写法和选词。事实上文言在很长的历史时期内都是比较通俗易懂的，只是在清代特定的文化历史环境下逐渐腐朽。
说白了，白话本身就只是直白的意思。。。

**Comment by AshyAzure** [comment]
而且，不同语言有不同语言的优势。文言文在它本身的文法结构上和紧凑性显然比现代汉语更加优秀（当然，这需要wenyan-lang能更多吸收文言的优秀元素:P）。
当然，如果你坚定认为：白话文=普及知识，文言文=愚民，那么易语言欢迎你( ･᷄ὢ･᷅ )

**Comment by yanzhao77** [comment]
坦率的讲，就计算机语言和英语，差不多也是白话和文言文的区别，这个其实关系不大，
