### ISSUE TITLE
how did render.js work? it looks elegant XD

### ISSUE THREAD

**Issue by zzz6519003** [LingDong-/wenyan-lang#313]

**Comment by LingDong-** [comment]
Thanks for your interest, `render.js` is quite straightforward, it just takes every character of the string it is given, calculate its correct position, and draw it onto the [SVG](https://developer.mozilla.org/en-US/docs/Web/SVG).

**Comment by zzz6519003** [comment]
> Thanks for your interest, `render.js` is quite straightforward, it just takes every character of the string it is given, calculate its correct position, and draw it onto the [SVG](https://developer.mozilla.org/en-US/docs/Web/SVG).

I thought there were some magic(libs...) under the hood
