### ISSUE TITLE
乘「甲」於「甲」。若其大於「乙」者。is incorrectly compiled

### ISSUE THREAD

**Issue by statementreply** [LingDong-/wenyan-lang#316]
Source code:

`乘「甲」於「甲」。若其大於「乙」者。乃止也。`

Expected:
```
var _ans1 = 甲 * 甲;
if (_ans1 > 乙) {
    break;
};
```

Actual:
```
var _ans1 = 甲 * 甲;
if (undefined > 乙) {
    break;
};
```

**Comment by LingDong-** [comment]
Hi, `其` is not supported in `if` statements yet. But it should be very soon because I'm fixing these kind of errors right now.
Thank you very much for bringing this up.
