### ISSUE TITLE
Unexcepted results from loops

### ISSUE THREAD

**Issue by Starmys** [LingDong-/wenyan-lang#34]
I tried following scripts
```wenyan
吾有一數。曰三。名之曰「甲」。
吾有一數。曰五。名之曰「乙」。
為是「甲」遍。
	加一以「乙」。書之。
云云。
```
And got "六 六 六". It should be “六 七 八”, right?

**Comment by LingDong-** [comment]
Hi there,

Good question. Notice that `加一以「乙」` does not mutate 「乙」. It corresponds to `乙+1`, not `YI++`. Therefore, you need to re-assign the resultant value back to 「乙」. The correct way to achieve what you want would be:

```
吾有一數。曰三。名之曰「甲」。
吾有一數。曰五。名之曰「乙」。
為是「甲」遍。
	加一於「乙」。昔之「乙」者。今其是矣。
	吾有一言。曰「乙」。書之。
云云。
```

Thanks.
