### ISSUE TITLE
提议規範一下標點符號。

### ISSUE THREAD

**Issue by liangei** [LingDong-/wenyan-lang#348]
作为一个有强迫症的人 看了通篇都是句号 好难受
希望規範一下標點符號。。

例如：
吾有一數，曰三，名之曰「甲」。
吾有三數，曰一、曰三、曰五，名之曰「甲」、曰「乙」、曰「丙」。

這樣閱讀比較舒服，也符合符號在句子中的作用。

**Comment by LingDong-** [comment]
Hi, please see the discussion on #129, thanks!

**Comment by antfu** [comment]
Fixed in [v0.1.2](https://github.com/LingDong-/wenyan-lang/pull/416). Closing now. Feel free to reopen it if you got any questions.
