### ISSUE TITLE
CLI improvements

### ISSUE THREAD

**Issue by antfu** [LingDong-/wenyan-lang#353]
As this project kind of a scripting language. Make the cli direct executing code might be a better default behavior.

For example, `node` and `python` run code without any parameters in the cli.
```
node helloworld.js
```
```
python hello.py
```

I think we may have something like

**Executing**

```
$ wenyan helloworld.wy
> 問天地好在。
```

**Compiling**
```
$ wenyan helloworld.wy --compile --output .
// Write to helloworld.js
```
or a new cli 
```
$ wenyanc helloworld.wy --output . --lang py
// Write to helloworld.py
```

Would love to make a PR!

**Comment by LingDong-** [comment]
@antfu Sounds very reasonable. Please feel free to make a PR! Thanks a lot.

**Comment by liangei** [comment]
能否也将此处译为中文呢？
例如：
文言 将 helloworld.wy 输出 译为 py

**Comment by antfu** [comment]
@LingDong- Would you like to make the `executing` and `compiling` into two different cli commands (for example `wenyanc` for compiling) or just one cli but default to `executing`?

**Comment by LingDong-** [comment]
I think one command would be sufficient, let's just make the mode default to execute.
Thanks!

**Comment by antfu** [comment]
@liangei Unicode in the command line may not be compactable to some OS. If your os supports Unicode as the command you can set alias by `alias 文言='wenyan'`. I would suggest not to use Unicode for cli by default. Thanks.
