### ISSUE TITLE
增加木兰诗支持

### ISSUE THREAD

**Issue by chenghonour** [LingDong-/wenyan-lang#36]
{唧唧复唧唧，木兰当户织}应该编译为：定义一个叫户的类，织是户的方法，唧是织别名，木兰是户的实例，然后在一个循环里木兰把唧执行了四次[偷笑]

**Comment by xiaodit** [comment]
哈哈 有趣

**Comment by Ldada** [comment]
可以作为增强for循环来使用啊！
