### ISSUE TITLE
[Feature request] Hide compiled code of std lib from Online IDE

### ISSUE THREAD

**Issue by statementreply** [LingDong-/wenyan-lang#371]
Importing 算經 generates 300+ lines of code (1000+ on my WIP version of 算經) in compilation output window. This makes it hard to find compilation result of the input code, and breaks page formatting.

**Comment by LingDong-** [comment]
@statementreply Good idea! I just added the feature. Now there is a checkbox saying "hide imported code" on the online IDE.

8a4d0d11925b5e01b6cd9c6ea2369ad988517cfe

It uses a magic comment to do the trick. Prettier solutions in the future.

Thanks!

**Comment by antfu** [comment]
@LingDong- Maybe we can have more readable comment markers like:
```js
/* _____wenyan_stdlib_start_____ */
// ...
/* _____wenyan_stdlib_end_____ */
```
It can be beter handled by other tools as well. And I would like to add this feature to the vscode extension!

**Comment by LingDong-** [comment]
@antfu, the compiler is called recursively, so it has no idea if it is currently compiling a stdlib, a user-imported program, or the main program, and if the imported module also imported a module itself, the structure is going to be nested. Technically I can pass down a flag telling the next recursion that it is not the main program, but I'm not sure if I want to complicate the arguments just for this.
Perhaps we can do `/*_____imported_module_end_____*/` for any module. What do you think?

**Comment by antfu** [comment]
> flag telling the next recursion that it is not the main program, but I'm not sure if I want to complicate the arguments just for this.

For this, I would suggest an internal `compile` function for that. Things like `resetVarCnt` should also be in it. The public exported `compile` will be a wrapper of the internal one with fewer arguments.

> Perhaps we can do /*_____imported_module_end_____*/ for any module

You are right. Since imports are not necessary to be in stdlib. This makes more sense. But IMO I would add a prefix `wenyan` to be more distinguishable.
