### ISSUE TITLE
Use Jest to automatically test the program

### ISSUE THREAD

**Issue by calpa** [LingDong-/wenyan-lang#38]
Instead of checking the error by human, we can use `Jest` to test automatically.

For example:
```
吾有一數。曰三。名之曰「甲」。
```

This sentence should init a variable call `甲`，and it is 3

**Comment by LingDong-** [comment]
Great idea, now that pull requests and new examples proposed all the time, automated testing would be very helpful.
I'm not very familiar with Jest, if you could help out and make a pull request I'd really appreciate it. Otherwise I can look into Jest and and see what I can do.
Thanks!

**Comment by LingDong-** [comment]
Someone submitted some tests using Mocha: https://github.com/LingDong-/wenyan-lang/pull/61

As I don't have a preference, perhaps let's go with Mocha, unless someone can think of some fundamental superiority for Jest ;)

**Comment by secminhr** [comment]
何不試以文言測之？

**Comment by antfu** [comment]
Closing now. Since we are already using Mocha for testing. If you got any questions, feel free to reopen it.
