### ISSUE TITLE
支持楼主这样的行动,但对楼主的目的不敢恭维.

### ISSUE THREAD

**Issue by qwas982** [LingDong-/wenyan-lang#380]
支持楼主这样的行动,但对楼主的目的不敢恭维.

我认为这是华而不实的,不是以实用为目标.
我觉得中文汉字汉语编程一样可以出现C++,java,这些能工业生产的强工程化语言.

究竟该怎么做?

要回答这个问题,

你需要一些准备工作,
首先,你需要理解什么是,二元论,这是二进制世界的哲学指导思想,起码我是这样认为的,
其次,你要明白什么是递归,自举,这两个概念,那么你要锻炼自己的想象力,掌握抽象.
接下来,你要理解编程(程序)的本质(工程视角),-函数-,
我说的这个函数概念不是冯氏结构(冯诺依曼)中的或图灵机的函数概念,而是兰姆达演算所描述的函数概念,

好了,有了上述基础,
你还需要语言学相关的知识,乔姆斯基的理论你得略知一二,不要紧,搜索就是(认真脸)
接下来,你需要理解形式语言,形式语言基于形式逻辑,
最后就是数据结构与算法相关的知识了,

以上说的是理论基础,
接下来我要泄露天机(真理)给你,
/-------------------------------------
所谓编程语言,这个工具,它不是"语言",它是文字,用更通用的说法是,-符号-,
这是一套人造字符,用来代表形式逻辑所要传达的内涵,
它分语法标准(规范),和语义实现,
标准偏理论,实现偏工程,
每一个语言只有一个标准,但有很多个实现,
语言的标准是一种规则,用于如何表示/描述数据,和操作/运用数据,
语言的实现是一种虚拟的抽象机器,用于将规则翻译给处理机,

如何表示/描述和操作/运用数据,就是数据结构和算法所要完成的工作,
如何翻译规则,就是编译器的工作,
/----------------------------------------
我想你肯定对编译器更感兴趣一些,那我就说说这个,
其实编译器是很简单的,它来来回回就那几个概念,只不过被桩哔的人夸张化罢了,
编译流程有几个经典步骤,我就不说了,你可以搜索,到处都是,
我用我的表达描述下,它分三步,
符号表,语法树,指令,
这三步用数据结构来表示,就是,
链表,二叉树,栈,
它通过这三步将源代码翻译为处理机能识别的形式-指令,
机器识别和处理的是指令,指令由操作码加操作数表示,
机器接受的是逻辑,而不是二进制,二进制只是机器的承载,
还有,符号表很重要,它的存在就是为了转化符号到数字的对应关系,

说到这里,你可能就清晰明白起来了,要创造中文编程(我称之为中文汉字汉语编程),
你只需要设计一套符号,加一套指令系统(指令集合,也就是指令集),
这套符号是面向人类可读的,
这套指令系统是面向机器可识别的,

符号你不是非得用西文字母文字来表示,你可以用汉字或象形文字,甚至图形来表示,
假如你要设计出符合汉语之语法和语素的语义,
那么你得模仿乔姆斯基,收集和抽象出能描述汉语常用语的最小集,
所以首先你需要研究一遍汉语的语法,
之后将浓缩出的最小集进行逻辑转化,如何转化?
你需要学习谓词逻辑,
当你完成这一步之后,你就可以根据你转化后的这套承载了汉语语法的逻辑语义,
去设计一套适用于表达形式逻辑的语法标准,
这个标准正如我前面说的,你既可以用象形文字作为表示符号,亦可用字母文字,

这是假如你要创造语法标准的前提下,就稍微难了点,
假如你只是想用汉字文字实现编程开发,
那么你也可以用现在众多编程语言的语法标准,做一个工程实现,
即开发一款编译器,

如果你不想用字母编程语言,你可以用易语言来开发,不要被业界对易语言的偏见所迷惑,
易语言是图灵完备的,它与业界现有的各种编程语言没有任何功能差异,
易语言与现有语言,语义等价!

王垠和RednaxelaFX的文章要多看多读多想,TA们都是研究编程语言的大牛,
一个偏理论,一个偏工程,

我上面说的很多知识点展开来都是很长的文章,你可以搜索,
但你要懂得从文章中提取出真理,
真理往往都是一句话两句话就能说完的,
长篇大论的裹脚布,就没必要一字一句用放大镜看,耗费时间精力人生,

编写程序,无论用字母还是汉字,本质都是如何使用数据结构,
操作数据结构即为算法,
将你要解决的问题进行伪代码分析,然后用数据结构去把分析结果进行分门别类地组织起来,
之后根据操作步骤的需求来使用何种算法,你也可以创造全新的算法,也就是想出新的步骤,
这是相对于人可读来说的,
而机器可识别的就是一串串的指令,被称为指令序列(队列),每一条指令代表一个细微的步骤,
这就是程序的本质,

最后一句,
不要过于关注人事物时地的表象,
要专注注意力于内在,

**Comment by UltimatePea** [comment]
> 这是假如你要创造语法标准的前提下,就稍微难了点,
> 假如你只是想用汉字文字实现编程开发,
> 那么你也可以用现在众多编程语言的语法标准,做一个工程实现,
> 即开发一款编译器,

这段论述中
你假设了
（1） 楼主想创造一套语法标准
（2） 楼主只是想用汉字文字实现编程开发
所以你得出结论
（3） 楼主可以用现在众多编程语言的语法标准， （做一个工程实现，即开发一款编译器）

但（1）和（3）是冲突的，楼主想创造一套语法标准，必不可以用现在众多编程语言的语法标准

**Comment by Purstal** [comment]
这本来就不是以实用为目标的项目呀

repo 的第三个标签就是 `esoteric-language`

**Comment by CurvedArray** [comment]
你的想法需要一个团队，一个组织甚至一个机构，而不只是作者一个人

**Comment by cuixiping** [comment]
题主写了这么长一篇，但是，很明显，题主完全没有理解作者的意图，也完全没有理解大家为什么支持这个项目。

题主说【我认为这是华而不实的,不是以实用为目标.】，题主认为【不是以实用为目标】就等于【目的不敢恭维】么，那题主的要求还是低了些，停留在吃饱肚子的层面，这个项目带来的，是快乐。

声称要【泄露天机(真理)给你】，未免有些自负了。
题主自己的【全新中文字符编程语言】的见解，我倒觉得是一条歧路，就不细说了。

**Comment by AlexanderMisel** [comment]
我想说，LingDong应该是吧主吧，你才是楼主呀。楼主应该不太会用markdown吧。

**Comment by cuixiping** [comment]
> 我想说，LingDong应该是吧主吧，你才是楼主呀。楼主应该不太会用markdown吧。

是的，他这个用词错误。

LingDong是作者（吧主）。
qwas982 是题主（楼主）。

**Comment by qwas982** [comment]
哈哈,欢迎各种多元化的观点,
欢迎大家求同存异地发表各自的见解,

**Comment by qwas982** [comment]
我认为编程开发说白了不过是文字工作,
从上面的回复来看,还是能看出中国人文人相轻的实际情况.

**Comment by liyishuai** [comment]
I didn't get the point of this issue. It is the repository owner who decides the purpose of this project. Are you trying to educate them? As a novice programmer, I haven't learnt anything new from what you've said.

**Comment by sandyzikun** [comment]
我觉得，lingdong作为一个中国留学生，用作为程式员用自己的方式弘扬中国传统文化，本身是一件值得推崇的事情，他又不是只是为了蹭热度或者靠这个来赚钱赚完走人之类的。

而且在我看来，这个项目拥有巨大的潜在价值，wenyan算是极其贴近自然语言逻辑的，在某种程度上也能降低文普通人入门编程的门槛。

至于投入工业化生产。。。我想你也未必现在还能见到某个知名机器学习项目用什么`BASIC`对吧，那我们就要说`BASIC`一文不值吗？对吧。

**Comment by Lotayou** [comment]
@LingDong- Consider adding a "gainsay（杠精）" tag for these guys :P

**Comment by GeoITwinkle** [comment]
大家移步国内知乎就知道完全没有必要理会题主了。
https://www.zhihu.com/question/66642888。
计算机民科大神麻烦右上角点X，走好不送。
@LingDong- 建议直接Close/Delete issue.

**Comment by GeoITwinkle** [comment]
> 我想说，LingDong应该是吧主吧，你才是楼主呀。楼主应该不太会用markdown吧。我觉得你说话的口吻很像中国高校老师。

他是国内计算机民科的大神之一，可出名了。
https://www.zhihu.com/question/66642888

**Comment by qwas982** [comment]
@GeoITwinkle  
是不是民科,不是你定义的,
我起码在探索新道路,你做了什么?

你觉得你跟这个知乎链接里的那些损人不利国与族的人有何区别呢?
关于搞中文汉字汉语编程,我起码给出了论据,
你给出了什么?
对人不对事地搞人身攻击加否定多元化的一言堂?你算哪根葱?可笑,
杠精不就是说你这类人?杠精你好,杠精再见.

**Comment by liyishuai** [comment]
@qwas982 您确实在程序语言领域颇有造诣。我建议您去卡内基梅隆大学应聘教职，开堂课教教项目作者该怎样探索新道路。

**Comment by cuixiping** [comment]
I hope @LingDong- close this useless issue. We are disturbed by it.

**Comment by qwas982** [comment]
看来讨论中文编程,会不由自主地滑向毫无意义的消极,无建设性,无正面积极的讨论,最后就是人身攻击,
我倒发现一点,只要是为民族志向考虑的言论和观点,几乎都会一边倒地遭到攻击,
文人相轻果不其然,窝里斗实属厉害.
可能从1840年以来,甚至被蒙元满清统治以来,奴性已经在膝盖上生根发芽,
中国又是时候需要出现一些有血性的人物了,当然,我不是说我,不过我在向这个方向奋斗.
@LingDong- 
可以关闭这个问题了,请关闭它吧.

**Comment by LingDong-** [comment]
As you guys wish :)

**Comment by yanzhao77** [comment]
@qwas982 如果你能做出像作者一样或者比他更好的编程语言，没有人会吝啬自己的掌声，但恰恰相反，我只看到你将希望寄托于c#做出一个中文版，支持中文在现在而言，已经没有多大的意义，utf-8的出现，中文的关键字和变量名都不是问题，但是真正意义上的中文编程很少，作者所开发的文言文编程并不完美，但是会给后来的人一个方向，而你又做了什么呢？你没有为这个事业做任何有实际意义的工作，哪怕像评论区中的同仁一样，做一个js转换的工具，也是实实在在的贡献。坦率的讲，你就想亮剑中的田墨轩一样，空口大道理张嘴就来，讲的头头是道，让他去给贫下中农扫盲却万万不肯，认为是轻贱了自己的身份，说是文人相轻，如这样的文人，还是少点了好，任何时代，人实实在在做出事情的人，永远会被尊敬，如钱学森，如袁隆平

**Comment by hzqd** [comment]
此issue作者的逻辑混乱程度不忍直视

**Comment by qwas982** [comment]
@yanzhao77  你就跟王垠描述的那类人一样,http://www.yinwang.org/blog-cn/2019/12/26/success,去看看吧,说的就是你这类人, 你在向我要现成的成品,这说明你是伸手党,这是一,二是你在要求我按照你的要求达到wenyanlang作者的标准,嗯,严于律人,不知他人苦,还在劝人大度,当你这样要求他人的时候,先照照镜子.

**Comment by yanzhao77** [comment]
@qwas982 第一，你说的网址挂了，第二，我确实实力有所不逮，所以我会虚心向人学习，在自己知识的范围内提问，并努力给项目添砖加瓦，而不是向你一样，上来就是不知所云的讲编译器应该这样那样，如果你是大牛，我自然无话可说。

**Comment by cuixiping** [comment]
这个帖子太烦了，大家不理会此人，才是上策。

**Comment by qwas982** [comment]
@hzqd 看不懂别人的文章可以选择不看,懂吧,求你来看了吗?

**Comment by qwas982** [comment]
@yanzhao77  已经给你编辑过了,去看吧,
你是想道德审判我吗?
我可不是在讲"编译器应该如何如何," 看不出我的支持文稿,说明你看不懂,并会错意.

**Comment by UltimatePea** [comment]
大家都有发言的权利嘛，好好讨论，不要吵架。

**Comment by liyishuai** [comment]
This thread has derailed into endless nonsense irrelevant entertaining flood. I'd suggest never taking this issue seriously unless you are smart enough to understand what the author is trying to express, **if any**.

**Comment by UltimatePea** [comment]
看样子大家不太理解题主，我想贡献一下自己的一份力量，总结一下题主所表达的观点。如有错误，还请题主指出。

作者认为，语法计算和实现是三位一体的，不可区分对待。并且，计算逻辑与人的价值观和精神世界也有联系，计算机的语言与人的世界观以及世界的组织方式也是相互协调统一的。基于此理解，作者认为设计一门编程语言必须面面俱到，仅有一个正则语法却没有自己的底层实现，就如同一个人徒有外表而缺乏内涵，是一个残缺的编程语言，不是一个纯粹的工业编程语言（如C++，易语言等）。

**Comment by liyishuai** [comment]
感谢翻译。

此观点领先我们所处的整个时代。
从希格斯提出理论到CERN发现对应的玻色子隔了半个世纪；
也许我们也需要等几十年，程序语言如作者描述的那样富有内涵，再给作者颁发一个图灵奖。

**Comment by qwas982** [comment]
@liyishuai  
你觉得你在这里讥讽很有成就感吗?
讥讽使你产生成就感,令你产生高潮是吗?
呵呵,
你当然可以继续这样啦,这是你的自由嘛,
我不干涉你的自由.

**Comment by qwas982** [comment]
@UltimatePea 
不要会错意,
我没表达这种意思,`作者认为设计一门编程语言必须面面俱到，仅有一个正则语法却没有自己的底层实现，就如同一个人徒有外表而缺乏内涵，是一个残缺的编程语言，不是一个纯粹的工业编程语言` 
我发在这里的文章是一种思想交流,也可以当做是建议意见,随感感想,
没有要求任何人的意图.

我在前面有几楼说过,欢迎大家多元化讨论,我已经表达过我的态度了,奈何杠精和充满优越感的人太多,大搞文人相轻,窝里斗,最后也如TA们所愿地关闭了这个帖子.
我觉得我没什么对不起任何人的行为和言行.

交流思想,发散讨论,也是意即希望寻找出一种中文汉字汉语编程的可行性道路途径来,
没有这个意愿的,大可绕道,
这里从没强求强迫任何人做什么,想什么.

**Comment by liyishuai** [comment]
我表达能力不太行，还得请作者来教教我怎样说话既逻辑清晰又不算讥讽，目前这两点我无法同时做到。

**Comment by liyishuai** [comment]
如果你确实想表达些想法，请换用让读者更容易理解的表达方式，目前我是没看懂你想说什么。
只有聪明人能够理解的事物，那是皇帝的新衣。
倘若一般人需要学习些基础知识再来读你写的东西，烦请列个参考文献，并告诉读者需要学习其中的哪些概念。

总之，如果你想被人理解，请给人理解你的可能。

**Comment by qwas982** [comment]
@liyishuai 

唉....我不知道你是在这里藐视轻蔑还是想真诚交流,
你自己也表达了别人的意思难懂难理解,
更何况是代码,
那么,同理可证,你就可以以此为据,
是不是可以说明,中文汉字汉语编程的代码可读性更强?
你先不要考虑外国人的感受如何,咱中国现在还是发展中国家,
更有中兴华为前车之前,还有贸易战,还有996.icu这种涉及到咱劳动者自身的情况,就更不应该量中华之物力结与国之欢心,
再加上咱们民族的文化与传承,汉字拉丁化的历史你应该去瞧瞧.
先认真地思考下这个问题.

**Comment by liyishuai** [comment]
恕我驽钝，还是没看懂你想说什么。

有哪位好心人愿意翻译一下吗

**Comment by cuixiping** [comment]
> 恕我驽钝，还是没看懂你想说什么。
> 
> 有哪位好心人愿意翻译一下吗

別理他就行了

**Comment by qwas982** [comment]
原创发文,


我领悟到我的业余生活主要是在斗争,而不是在自学,我却在自我欺骗自我催眠自己在自学.

在最开始,我只是觉得在血汗工厂当农民工打工实在是太没前途了,在流水线装配线上的重复劳作,不但不能令我进步,反而还因那种机械的简单循环使我觉得我与人性与人群社会越来越远,所以,我想利用可怜的业余时间学点有价值的知识,我想改变我的命运,就如同天下所有想改变命运的斗士一样.而知识是个比较广泛的概念,因有价值的知识,那就有无价值的知识,是文科还是理科?技术还是非技术?最后经过对比,我选择了技术,也是最难的一条路,总结过去这几年的经历(12年以后至今),我以为我是在利用业余时间学习一些技术增强技能改变命运,但实际上,我发现我大部分时候都在从事[斗争],我觉得我被不可抗拒的社会风气拉入了一种沼泽泥潭,不能自拔,因为现在大部分舆论斗争都转移到了线上,而又因我要学习和查阅各种学习材料,我就不可避免地会被卷入其中,这其中以境外邪恶势力,如女权主义,婚恋市场买卖化,分裂分子为主,国内的"黑五类",黄赌毒,各种热点新闻中的社会达尔文主义,精神资本家等等太多,我发现了一个显著的特点,所有的这些对象都不是表面现象看起来那么粉饰太平地简单,TA们的背后都有资本巨手在助推,而我自己完全是自发地站在无产阶级革命大众的立场进行斗争的,刚开始我并没感觉到我与敌对势力的力量之悬殊,但经过这么多年下来,被删封禁各种打击后,我才明白,我到底是有多弱势,因此我开始寻找与我有相似行为的朋友,和组织,但找到的情况令人心凉和遗憾,因中国左派与国外左派是不同甚至相反的,我发现左派并不等于≠无产阶级革命群众,我加入了很多偏左派的群体,但是也遭到了打压,我发现TA们大多都有一个特点,就是脱离实际,TA们大多按照书上的理论去思考,几乎不实践,完全不知社会底层劳苦大众,如我这样经常驻于血汗工厂打工究竟是过着怎样艰难困苦的生活,因此我与TA们辩论,历史唯物,唯物辩证,只可惜,大多数情况下到最后都是会发展都攻击,人身攻击,对人不对事,有些人甚至会带有恶意,而不是对事不对人,就事论事地纵深探讨,最后就是被删封禁,更不可能有为国家和民族考虑的情况存在(如内忧外患,996/251等,压迫与剥削,中兴华为前车之鉴,贸易战等等),而我又以其人之道还治其人之身,坚决地反击之,至此,我才明白/醒悟,我这几年的行为到底有多无意义,我才发现我不过是被杠精和喷子同化了罢了,不断地在打嘴炮而已,我也不过是在瞎喷瞎杠,做的是些毫无价值的事,我每次都告诫自己要将自己的时间精力人生专注于在有价值的技术知识的学习上,但每次都会各种斗争吸引,它就像是强力磁铁一样,我就分析为什么会这样,最后发现,因为我的阶级属性使然,我本质上就处在这个无产阶级的性质上,那么,我对剥削和压迫就相当敏感,一点异味我就能嗅到,于是就身不由己地陷入了斗争激烈如火如荼,实际现实生活陷入更艰难的处境,自己的目标和追求更是陷入瘫痪,我觉得我进入到了一种痛苦的拖延拖拉拖沓之中,于是我自问自己,我该怎么办,这些继续下去不是办法.我尝试过加入守贞(通假字,通真、正),学习他们的一种自律来缓解我的现状,我希望严于律己,进行自控自律,效果还是有的,只是居于这广泛的魔幻现实主义世界中,会很快中和其效果,直到现在,我也并没找到更新的方法来规矩/规则自己,我只有尝试加码守贞,禁欲自控,起码还是能形成一种保护屏障的.
虽然我的业余专业学习进度很慢,但还是有一定的学习成果的,与前者("斗争")经验相辅相成,使我领悟到,我需要找到真理一样的存在,这个寻找的过程加深了我理解科学/数学/哲学相关的认知,而学习和研究编程语言,编程技术,不断接触代码的内涵,使我加深了这一点认识,同时我也认识到毛主席的思想经过历史和时间的检验也如科数哲一样是无限接近真理的,这些近似真理令我觉得要比守贞更有用一些,我不是说守贞就低劣了,我并没这个意思,对帮助过我的有价值之知识经验,我还是心存感激的,于是我写下这些归纳总结,也算是我的过往经历之学习笔记吧.顺便说一句,我参加中文编程(我称之为中文汉字汉语编程)相关群体的奋进发展,也是基于我在现实中所处之阶级现状而展开的,所有事情都是有因果有根源的,我不会无缘无故无中生有突然就这样了,所以每当遇到贬低汉字编程的相关舆论,我自然也就自发地参与了相关的斗争,在这其中我也认识到汉字编程对于广大无产阶级大众的巨大作用和优势,因为真正在现实中被压迫被剥削的无产阶级人民是没有时间和精力和机会去学习真正有价值的知识技术的,无产阶级想学习进步的成本太高了,特别是基于现实社会的阶级现状来看,而我只是有意识地有幸地找到了这点,我主动自发地挤出时间精力去寻找改变命运的出发点使我认识到汉字编程对无产阶级人民的有益性,所以我也继续发挥余热去主动宣传它的价值,奈何受艰难现实枷锁钳制的广大劳苦人民很难理解到这种价值,因为这距离他们太遥远了,我想授人鱼不如授人以渔的出发点并不能为他们所理解,于是各种冲突矛盾还是不可避免地斗争发生了,唉,心累.
我想我作此文也是为了警醒自我,应时刻关注自己是否在收心专注于自己真正重要的事上吧.

**Comment by UltimatePea** [comment]
@qwas982 你能用Chomsky方法分析一下中国古文语法么？

**Comment by qwas982** [comment]
@UltimatePea  
不能,
我也不会,
用汉字实现编程的现实社会问题不在于汉语自然语言的语法如何,
西方人用字母文字实现编程也不是根据英语或西欧自然语言的语法去设计的,
因为实现编程所用字符的指导方法根本不在于自然语言的语法.

红色江山变官僚资商特色江山,要想认识到问题的根本,先看看自己的屁股在哪里,试问自己是不是改开党,这决定了你我他是如何认识现实社会问题的,先了解下生产资料,生活资料的区别,生产关系,生产力各指的是什么,计算机软硬件各行业也不例外,这些行业也没有脱离人类社会与人类生产劳动的范畴,先认识到自己是资产还是无产,自己是劳苦大众,还是食利阶层,生存竞争,生存竞争呐,可以看出,世界上各大生存集团是客观地独立存在的.忘战必危,好战必亡.

我引用这段是想提示阅者计算机的目的性,
计算机的发明和使用是分开了的,现代意义上的计算机最初目的是为了密码学,为了-解战地密文,
它就是随战争而生的,而人类历史为何会有不间断的战争,所以说编程语言不是"语言",研究中国古文语法并不能获得根源的知识,是与目的性背道而驰的,这样研究下去研究到宇宙毁灭也研究不出什么,

**Comment by liyishuai** [comment]
Let's thank the issue author for bringing real diversity to GitHub: some people code, others only talk.

Unaware of any political purpose of my research, I must be a fake computer scientist and should quit school immediately.

**Comment by qwas982** [comment]
@liyishuai 
又是你这厮,一会儿英文字母 一会儿汉字,自我感觉良好,你觉得你很有优越感很伟大很受欢迎吗?哪凉快哪呆着去吧,我不欢迎你!

**Comment by liyishuai** [comment]
您是没看懂我英文说了什么，完全没有自我感觉良好的意思，翻译过来是这样的：
> 感谢您让我认识到世界的多样性：有的人闷声写代码，有的人谈笑风生。
您的教导使我意识到自己研究的东西毫无意义，我应立即办理退学手续。

**Comment by qwas982** [comment]
@liyishuai   @cuixiping  

想做事的做不成,想求生存的求不了.
活腻了的一大堆还在阻止做事的,
我求你来讨论了吗?你是瘟神还是咋的?尼玛半点自觉性都没有?
自个儿不想理睬还一直在这里回复?就算是苍蝇也不带这样恬不知耻吧!感受不到他人的厌恶吗?
速速离去,苍蝇去别处叮.

**Comment by qwas982** [comment]
@cuixiping  
我发的每一条都有你点反对,你特么是屎吃多了吗?
跳梁小丑,哗众取宠.

**Comment by qwas982** [comment]
果然是马善被人骑,人善被人欺,

这天底下还是行恶者居多,地狱空荡荡,恶鬼在人间.

对待邪鬼恶毒有癫瘾的"人",真的是要以牙还牙,以眼还眼,以血还血.以其人之道还治其人之身.
否则就天下善良的人过不下去.
