### ISSUE TITLE
Standard Library Cheatsheet

### ISSUE THREAD

**Issue by antfu** [LingDong-/wenyan-lang#383]
Hey guys, Merry Christmas! ☃

## Describe your issue/suggestions

Since we already have a [Syntax Cheatsheet](https://github.com/LingDong-/wenyan-lang#syntax-cheatsheet). I propose to adding a **Standard Library Cheatsheet**  helping users to better reference the functions in the standard library and contributors to quickly check if a function has been implemented already or not.

For example:

### [算經](https://github.com/LingDong-/wenyan-lang/blob/master/lib/%E7%AE%97%E7%B6%93.wy)
| Wenyan | Javascript Equivalent |
| --- | --- |
| `圓周率` | `Math.PI` |
| `正弦` | `Math.cos` |
| ... | ... |

## Before you open the issue, Please be sure ALL the items in the following list are checked

- [x] If this is a feature request, my request is NOT listed [Here](https://github.com/LingDong-/wenyan-lang#feature-requests)
- [x] If this is a bug report, my bug is not listed [Here](https://github.com/LingDong-/wenyan-lang#known-bugs)

**Comment by LingDong-** [comment]
Merry Christmas @antfu , sounds like a great idea. I propose that we add it to a file separate from the main README, because I think it's going to be a really long list :)

**Comment by cuixiping** [comment]
We can auto generate the list from the source code comments like JSDoc.

**Comment by antfu** [comment]
@cuixiping That's a good idea! However we can only extract the function name in wenyan but not  the js equalvient. Otherwise we would need to add comments in the stdlib.

**Comment by cuixiping** [comment]
> @cuixiping That's a good idea! However we can only extract the function name in wenyan but not the js equalvient. Or we would need to add comments in the stdlib.

I agree to add comments in the stdlib.
