### ISSUE TITLE
Add url query support and history state support to online IDE

### ISSUE THREAD

**Issue by cuixiping** [LingDong-/wenyan-lang#386]
I did some changes to the online IDE page.

1. Add `<title>......</title>` to the HTML code.
2. Show Chinese in the examples list box.
3. Add url query support. So we can directly link to a specified example. For example, `http://wenyan-lang.lingdong.works/ide.html?example=hanoi` will open 「漢諾塔」directly.
4. Add history state support. So we can use the back and forward buttons of browsers to navigator examples when we changed the example from the list box.

![image](https://user-images.githubusercontent.com/1104492/71431896-5b1feb80-2710-11ea-88ac-891a61bf2909.png)

![image](https://user-images.githubusercontent.com/1104492/71431948-a803c200-2710-11ea-83ee-0349c2aad3dd.png)

![image](https://user-images.githubusercontent.com/1104492/71431904-62df9000-2710-11ea-8fc1-70beb5d51edc.png)

Should I commit the auto generated file `site/ide.html` to repo before I send PR?  @LingDong-

**Comment by LingDong-** [comment]
Hi @cuixiping,

Thanks a lot! Looks very cool 👍 . I think it is better to not submit generated `site/ide.html`. It tends to create huge conflicts. I can re-generate the page after merging pull requests.

**Comment by antfu** [comment]
Fixed in #400. Closing now. Feel free to reopen it if you got any questions.
