### ISSUE TITLE
施「某物」之「「某子物」」之「「某術」」doesn't work as expected

### ISSUE THREAD

**Issue by cuixiping** [LingDong-/wenyan-lang#402]
I want to write `var E = A.B.C(D);`
How to do it with wenyan?

I tried these
```
施「某物」之「「某子物」」之「「某術」」於「「某參數」」
夫「某物」之「「某子物」」之「「某術」」者。施之於「「某參數」」
```
They doesn't work as expected.

The following code works but does not like Chinese enough.
```
施「某物.某子物.某術」於「「某參數」」
```

## Checklist

Before you create this issue, Please make sure ALL the following items are checked

- [x] If this is a feature request, it's NOT listed [Here](https://github.com/LingDong-/wenyan-lang#feature-requests)
- [x] If this is a bug report, it's NOT listed [Here](https://github.com/LingDong-/wenyan-lang#known-bugs)

**Comment by LingDong-** [comment]
Hi @cuixiping, thanks for bringing this up!
Unfortunately, chained dots are not supported yet, what you can do now is

```
夫「某物」之「「某子物」」。名之曰「某某」。
夫「某某」之「「某術」」。名之曰「某某某」。
施「某某某」於「某參數」
```

I agree this is so verbose! Very soon the below will be supported:

```
夫「某物」之「「某子物」」。夫其之「「某術」」。施其於「某參數」。
```

And eventually chained dots might be added too.

**Comment by cuixiping** [comment]
Great! Thank you.
