### ISSUE TITLE
吾有一術。名之曰「JS转文言」。现已支持大部分 JS 语法转换。

### ISSUE THREAD

**Issue by zxch3n** [LingDong-/wenyan-lang#406]
@LingDong- Could this be counted as a contributed tool? 😄 

Project url: https://github.com/zxch3n/wenyanizer

### 进展

| Name | Status |
|:-----------------|:-------|
| JS Code Compiled From Wenyan | ✔    |
| Closure      |  ✔    |
| Control: While/For/If/Else      | ✔    |
| Object `var a = {a: 0, b: 1, c: 2}`  |  ✔  |
| Array `[[[0 ,2], [2, []]]]`     | ✔  |
| `+-*/`  | ✔  |
| `--, ++, +=, -=, /=`  | ✔  |
| Distinguish `a++` and `++a`  | ✔  |
| Wraping global object when necessary, such as `Math`, `JSON`  | ✔    |
| `console.log` | ✔  |
| `a.b = 3` | ✔ |
| NewExpression | ✔ |
| Function | ✔ |
| `this` keyword | ✔ |
| `a[b] = 3` | ✔ |
| ForOfStatement | ✔ |
| [Wenyan Lib](https://github.com/LingDong-/wenyan-lang/issues/290) | WIP |
| [Wenyan Nested Function Call](https://github.com/LingDong-/wenyan-lang/issues/322)  | ❌ |
| [Optimize Curried Function](https://github.com/LingDong-/wenyan-lang/issues/322)  | ❌ |
| RegExp | ❌ |
| switch | ❌ |
| bit op | ❌ |
| `null` `undefined` | ❌ |
| DebugExpression | ❌ |
| WithStatement | ❌ |
| `continue` | ❌ |
| debug exp | ❌ |
| ForInStatement | ❌ |
| throw try...catch...finally | ❌ |
| Modules (import, export, require) | ❌ |
| `===` (will be compiled to `==`) | ❌ |

**Comment by zxch3n** [comment]
It supports medium difficulty compilation now.

The screenshot is how it compile a program that solves sudoku

![image](https://user-images.githubusercontent.com/18425020/71478501-fdcc8d00-282a-11ea-86a6-2388d43c36c3.png)

**Comment by LingDong-** [comment]
@zxch3n This is so awesome. I just added it to the README. 👍

**Comment by zxch3n** [comment]
Thanks! :D

**Comment by cuixiping** [comment]
Amazing job!

**Comment by ZhaoYLong** [comment]
wow~ ⊙o⊙，👍

**Comment by sandyzikun** [comment]
fabulous!
