### ISSUE TITLE
bug:  assign value to an object's property

### ISSUE THREAD

**Issue by cuixiping** [LingDong-/wenyan-lang#421]
Input this code to online IDE
```
昔之「物」之「「屬性」」。今「甲」是矣。
```
Do I write correctly?

Output:
```
物["屬性"] = c;
```

Expect:
```
物["屬性"] = 甲;
```

**Comment by statementreply** [comment]
`昔之「物」之「「屬性」」者。今「甲」是矣。`

**Comment by cuixiping** [comment]
> `昔之「物」之「「屬性」」者。今「甲」是矣。`

Thank you! I was careless.

It will be better if there is a parse error.
