### ISSUE TITLE
Exec function in core package

### ISSUE THREAD

**Issue by antfu** [LingDong-/wenyan-lang#469]
## Describe your issue/suggestions

Currently, we only have auto numbers (and bools) conversion to hanzi in online ide. Not in cli, in browser runtime and other interfaces like vscode and sublime plugins.

I propose to extract the functionality and expose it in the core package allowing other interfaces to reuse this feature. This can make it more wenyan-ish without care about the internal details about it.

Meanwhile, this can also solve the floating-point testing issue, #457.

I would love to make a PR for this.

More related issues #465, https://github.com/antfu/wenyan-lang-vscode/issues/12

------

### New function `execute`

Allowing users to directly execute the source code through the API. This will be a simple wrapper of `compile` and `evalCompiled`

```js
function execute (source, options = { hanzinize: true, ...other options in compile })
```

### New function `evalCompiled`

This is basically all the changes happen. It will hijack the console.log and outputs hanzi result when the hanzinize option is set.

```js
function evalCompiled (compiledCode, options = { hanzinize: true })
```

### New CLI options `--hanzinize`

Default to true. Only works for executing mode

### New Browser Runtime script attr `hanzinize`

Default to true.

```html
<script type="application/wenyan" scoped hanzinize="false">
吾有一數。曰三。書之。
</script>
```

## Checklist

Before you create this issue, Please make sure ALL the following items are checked

- [x] If this is a feature request, it's NOT listed [Here](https://github.com/LingDong-/wenyan-lang#feature-requests)
- [x] If this is a bug report, it's NOT listed [Here](https://github.com/LingDong-/wenyan-lang#known-bugs)

**Comment by LingDong-** [comment]
👍 Sounds great! Please feel free to make a PR.
I'm not sure how readable the word `hanzinize` though, it sounds fun, but we might also consider something plain like `outputHanzi`. Let's think about it a bit more.
Thanks a lot and good luck with the PR, let me know if there's something I could help.
