### ISSUE TITLE
Proposal for new compile API

### ISSUE THREAD

**Issue by antfu** [LingDong-/wenyan-lang#471]
## Describe your issue/suggestions

Current `compile` API
```js
function compile(targetLanguage, source, options)
```

Proposed API

```js
function compile(source, options)

options = {
  lang: 'js' // by default
  ...other options
}
```

## Checklist

Before you create this issue, Please make sure ALL the following items are checked

- [x] If this is a feature request, it's NOT listed [Here](https://github.com/LingDong-/wenyan-lang#feature-requests)
- [x] If this is a bug report, it's NOT listed [Here](https://github.com/LingDong-/wenyan-lang#known-bugs)

**Comment by LingDong-** [comment]
Thanks, this sounds reasonable - shall we make it backward compatible, like checking if the first argument is a string that is one of the supported languages? 
I think there are quite a few stuff using the old api; But we can also change those stuff instead; Maybe let's do whichever is more convenient.
The current API isn't that bad though, is there something you're implementing, where this change will make things a lot easier?

**Comment by antfu** [comment]
Sorry, it's just a quick proposal and I didn't write explanations. The reason for this is for most consistency. The CLI has an optional target language. Executing will also work for js only at least for now. IMO, the first argument is explicit specifying target language seems not very intuitive for me. 

> shall we make it backward compatible, like checking if the first argument is a string that is one of the supported languages?

Agree with that. And we can throw a warning about API change when using the old API. Besides, we can dump a minor version like `v0.2.0` to show it's has breaking changes.

>  But we can also change those stuff instead;

I can do that. It shouldn't be too much.

> where this change will make things a lot easier?

`evalCompiled` and `execute` in #469 with use js for eval for now (other engines can be added later if it's possible). I think default to js makes it more reasonable.

**Comment by LingDong-** [comment]
Totally makes sense. Feel free to PR! Let me know if there's anything I could help.
