### ISSUE TITLE
来点面向对象编程的思路

### ISSUE THREAD

**Issue by yanlinlin82** [LingDong-/wenyan-lang#57]
重点是封装和继承，是不是可以考虑这段：

> 北冥有鱼，其名为鲲。鲲之大，不知其几千里也。化而为鸟，其名 为鹏。鹏之背，不知其几千里也。怒而飞，其翼若垂天之云。是鸟也 ，海运则将徙于南冥。

**Comment by LingDong-** [comment]
Nice. Please see also https://github.com/LingDong-/wenyan-lang/issues/31. I think the spirit is similar ;-)
