### ISSUE TITLE
子非🐟，安知🐟之乐。文言文连一个判断都做不了。

### ISSUE THREAD

**Issue by weaming** [LingDong-/wenyan-lang#65]

**Comment by pnjgyl** [comment]
wenyan | JavaScript
-- | --
若三大於二者。乃得「「想當然耳」」也。 | if (3>2){ return "of course"; }
若三不大於五者。乃得「「想當然耳」」。若非。乃得「「怪哉」」也。 | if(3<=5){return "of course"}else{return "no way"}
