### ISSUE TITLE
There is a small error on the project home page

### ISSUE THREAD

**Issue by gaowanliang** [LingDong-/wenyan-lang#85]
The first sentence on [this website](http://wenyan-lang.lingdong.works/)

> 文言, or wenyan, is an esoteric programming language that closely follows the grammar and tone of classical Chinese literature. Moreover, the alphabet of wenyan contains only traditional Chinese characters and 「」 quotes, so it is **guarenteed** to be readable by ancient Chinese people. 

In this sentence, "guarenteed" should be "guaranteed"

**Comment by LingDong-** [comment]
Thanks for spotting the typo! I can't spell :-P 
Just fixed: 5d3c6bc2f0ec629d50f6e28f5761847993caf7b0
