### ISSUE TITLE
Add comma support

### ISSUE THREAD

**Issue by rikakomoe** [LingDong-/wenyan-lang#93]
目前文言只支持句号这一种标点符号。我觉得可以支持读号`、`作为另一种分隔符，在语法上与句号无异，但使用起来可以使文章更清晰，可读性更强。

```
吾有一數、曰三、名之曰「甲」。
為是「甲」遍。
	吾有一言、曰「「問天地好在。」」。書之。
云云。
```

**Comment by duskmoon314** [comment]
I think this is a good idea.

In my memory, after Song, people used `、`and`。` and they mean `句读`. Usually `。`means a sentence is end in my memory.

Also, `之`, `乎` and so on can be taken into discussion.

> 又诗人以“兮”字入于句限，《楚辞》用之，字出于句外。寻兮字承句，乃语助馀声。舜咏《南风》，用之久矣，而魏武弗好，岂不以无益文义耶！至于“夫惟盖故”者，发端之首唱；“之而于以”者，乃札句之旧体；“乎哉矣也”者，亦送末之常科。据事似闲，在用实切。巧者回运，弥缝文体，将令数句之外，得一字之助矣。外字难谬，况章句欤。
> ——《文心雕龙》

**Comment by LingDong-** [comment]
Thanks a lot for the suggestions from both of you! I think you have a good point.
Will incorporate the `、` mark into the syntax. For `之` and `乎` I think it might be better to reserve them for actual functionality rather than no-ops.

**Comment by JLChnToZ** [comment]
I think you should add "，" too

**Comment by antfu** [comment]
Fixed in [v0.1.2](https://github.com/LingDong-/wenyan-lang/pull/416). Closing now. If you got any questions, free feel to reopen it.
