### ISSUE TITLE
吾有一術，名之曰「續一秒」

### ISSUE THREAD

**Issue by EtherDream** [LingDong-/wenyan-lang#94]
欲行是術，先取當下時辰，曰「甲」。加「甲」以千。名之曰「乙」，乃乙物，是謂「續命」之術也。

```js
new Date(Date.now() + 1000)
```

**Comment by Tangent617** [comment]
吾闻有一单，且此月汝单上有名。

**Comment by Yurunsoft** [comment]
19260817

**Comment by CodeAsPoetry** [comment]
孤弹丸久积，借汝头一用，以安军心

**Comment by YonguoS** [comment]
余常于土墙凹凸处，花台小草丛杂处，蹲其身，使与台齐；定神细视，以丛草为林，以虫蚁为兽，以土砾凸者为丘，凹者为壑，神游其中，怡然自得。

一日，见二虫斗草间，观之，兴正浓，忽有庞然大物，拔山倒树而来，盖一**癞虾蟆**，舌一吐而二虫尽为所吞。余年幼，方出神，不觉呀然一惊。神定，**捉虾蟆，鞭数十，驱之别院**。

**Comment by jiaxuml** [comment]
> 余常于土墙凹凸处，花台小草丛杂处，蹲其身，使与台齐；定神细视，以丛草为林，以虫蚁为兽，以土砾凸者为丘，凹者为壑，神游其中，怡然自得。
> 
> 一日，见二虫斗草间，观之，兴正浓，忽有庞然大物，拔山倒树而来，盖一**癞虾蟆**，舌一吐而二虫尽为所吞。余年幼，方出神，不觉呀然一惊。神定，**捉虾蟆，鞭数十，驱之别院**。

年长思之，二虫之斗，盖图奸不从也，古语云
“奸近杀”，虫亦然耶？贪此生涯，卵为蚯蚓所哈，肿不能便，捉鸭开口
哈之，婢妪偶释手，鸭颠其颈作吞噬状，惊而大哭，传为语柄。此皆幼时闲情也。

**Comment by Go7hic** [comment]
👓
👖

**Comment by kotritrona** [comment]
甚善
![](https://kotritrona.github.io/postbar/em/b38.gif)

**Comment by 15921483570** [comment]
吾有一马，名之曰【千里马】。【千里马】日行千里，有乃包裹一件。请门开之。

**Comment by Pamgo** [comment]
> 吾有一马，名之曰【千里马】。【千里马】日行千里，有乃包裹一件。请门开之。

你就是个送快递的
